"use client";
import { motion, useInView, AnimatePresence } from "framer-motion";
import { useState, useRef, useEffect } from "react";
import Link from "next/link";
import { Heart, Globe, Users, Menu, X, Star, CheckCircle2, BookOpen, HandHeart, Shield } from "lucide-react";
import "../premium.css";
const PRG=[{t:"Clean Water Initiative",c:"WATER",loc:"East Africa",d:"Wells and filtration systems for 50 villages."},{t:"Girls Education Fund",c:"EDUCATION",loc:"South Asia",d:"Scholarships and safe schools for 3,000 girls."},{t:"Forest Restoration",c:"ENVIRONMENT",loc:"Amazon Basin",d:"2 million trees planted since 2020."},{t:"Community Health",c:"HEALTH",loc:"Southeast Asia",d:"Mobile clinics serving 200 remote communities."}];
const SVC=[{icon:<Heart className="w-6 h-6"/>,t:"Direct Aid",d:"100% of designated donations reach the field."},{icon:<Globe className="w-6 h-6"/>,t:"Global Reach",d:"Active programs in 28 countries across 4 continents."},{icon:<Users className="w-6 h-6"/>,t:"Local Partners",d:"We work with established community organizations."},{icon:<BookOpen className="w-6 h-6"/>,t:"Transparency",d:"Quarterly impact reports with full financial disclosure."},{icon:<HandHeart className="w-6 h-6"/>,t:"Volunteer Programs",d:"Join field teams for 2-week impact experiences."},{icon:<Shield className="w-6 h-6"/>,t:"Verified Impact",d:"Third-party audited outcomes and spending."}];
const TM=[{n:"Dr. Amara Osei",r:"Field Director",q:"Every dollar donated here makes a tangible, measurable difference. I see it every day."},{n:"James McAllister",r:"Monthly Donor",q:"The transparency reports give me complete confidence that my donations matter."},{n:"Priya Sharma",r:"Volunteer",q:"My two weeks in the field changed my perspective on giving forever."}];
function Reveal({children,delay=0}:{children:React.ReactNode;delay?:number}){const ref=useRef(null);const iv=useInView(ref,{once:true,margin:"-50px"});return<motion.div ref={ref} initial={{opacity:0,y:20}} animate={iv?{opacity:1,y:0}:{}} transition={{duration:0.8,delay}}>{children}</motion.div>;}
export default function EssentialNonprofitPage(){
  const[s,setS]=useState(false);const[m,setM]=useState(false);
  useEffect(()=>{const h=()=>setS(window.scrollY>50);window.addEventListener("scroll",h);return()=>window.removeEventListener("scroll",h);},[]);
  return(<div className="premium-theme min-h-screen bg-[#faf5f0] text-[#2a1f14] font-mono selection:bg-[#d97706] selection:text-white overflow-x-hidden">
    <nav className={`fixed top-0 left-0 w-full z-50 transition-all duration-500 ${s?"bg-[#faf5f0]/90 backdrop-blur-xl py-4 border-b border-[#2a1f14]/5":"bg-transparent py-10"}`}><div className="max-w-[1500px] mx-auto px-6 md:px-12 flex items-center justify-between"><Link href="/" className="group flex items-center gap-3 text-xl font-black tracking-tighter"><div className="w-8 h-8 bg-[#d97706] rounded-full flex items-center justify-center text-white"><Heart className="w-4 h-4"/></div><span className="group-hover:text-[#d97706] transition-colors">ESSENTIAL // <span className="text-[#2a1f14]/30">GIVING</span></span></Link><div className="hidden lg:flex items-center gap-10 text-[10px] font-bold uppercase tracking-[0.3em] text-[#2a1f14]/30">{["Programs","Impact","About","Donate"].map(l=><Link key={l} href="#" className="hover:text-[#d97706] transition-colors">{l}</Link>)}</div><button className="px-6 py-2.5 bg-[#d97706] text-white text-[10px] font-black uppercase tracking-widest hover:bg-[#2a1f14] transition-all hidden md:block">Donate</button><button onClick={()=>setM(true)} className="lg:hidden"><Menu className="w-6 h-6"/></button></div></nav>
    <AnimatePresence>{m&&(<motion.div initial={{opacity:0,x:"100%"}} animate={{opacity:1,x:0}} exit={{opacity:0,x:"100%"}} className="fixed inset-0 z-[100] bg-[#faf5f0] p-8 flex flex-col pt-32"><button onClick={()=>setM(false)} className="absolute top-10 right-8"><X className="w-10 h-10"/></button>{["Programs","Impact","About","Donate"].map(l=><Link key={l} href="#" onClick={()=>setM(false)} className="text-5xl font-black tracking-tighter uppercase mb-10">{l}</Link>)}</motion.div>)}</AnimatePresence>

    <section className="relative min-h-screen flex flex-col justify-center pt-20"><div className="max-w-[1500px] mx-auto px-6 md:px-12 relative z-10"><Reveal><div className="px-3 py-1 bg-[#d97706]/10 border border-[#d97706]/30 text-[#d97706] text-[9px] font-bold uppercase tracking-widest inline-block mb-8">501(C)(3)_VERIFIED</div><h1 className="text-7xl md:text-9xl lg:text-[10rem] font-black leading-[0.8] tracking-tighter uppercase mb-10">Change<br/>Starts<br/><span className="text-[#d97706]">Here.</span></h1><p className="max-w-xl text-lg text-[#2a1f14]/40 leading-relaxed font-light uppercase tracking-widest italic mb-12">Transparent, direct-impact giving. Every dollar makes a measurable difference.</p><div className="flex flex-col sm:flex-row gap-6"><button className="px-12 py-5 bg-[#d97706] text-white text-[10px] font-black uppercase tracking-[0.4em] hover:bg-[#2a1f14] transition-all">Donate_Now</button><button className="px-12 py-5 border border-[#2a1f14]/10 text-[10px] font-black uppercase tracking-[0.4em] hover:bg-[#2a1f14] hover:text-white transition-all">Our_Impact</button></div></Reveal></div></section>

    <section className="py-40 bg-white border-y border-[#2a1f14]/5"><div className="max-w-[1500px] mx-auto px-6 md:px-12 grid grid-cols-1 lg:grid-cols-2 gap-24 items-center"><Reveal><span className="text-[10px] text-[#d97706] font-bold uppercase tracking-[0.4em] mb-6 block">About</span><h2 className="text-5xl md:text-7xl font-black tracking-tighter leading-[0.85] mb-8 uppercase">Real <span className="text-[#d97706]">Impact.</span></h2><p className="text-base text-[#2a1f14]/40 leading-relaxed mb-12">Founded in 2018, Essential Giving connects donors directly with communities in need. No overhead bloat — just transparent, effective philanthropy.</p><div className="flex gap-16">{[{v:"$12M+",l:"RAISED"},{v:"28",l:"COUNTRIES"},{v:"500K+",l:"LIVES"}].map((s,i)=><div key={i}><div className="text-3xl font-black text-[#d97706]">{s.v}</div><div className="text-[9px] font-bold text-[#2a1f14]/20 uppercase tracking-widest">{s.l}</div></div>)}</div></Reveal><Reveal delay={0.15}><div className="w-full aspect-square bg-gradient-to-br from-[#d97706]/10 to-[#d97706]/5 rounded-3xl flex items-center justify-center"><Heart className="w-20 h-20 text-[#d97706]/15"/></div></Reveal></div></section>

    <section className="py-40 bg-[#faf5f0]"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter uppercase leading-[0.85] mb-24">Our <span className="text-[#d97706]">Programs.</span></h2></Reveal><div className="grid grid-cols-1 md:grid-cols-2 gap-8">{PRG.map((p,i)=><Reveal key={i} delay={i*0.05}><div className="group cursor-pointer"><div className="w-full aspect-[16/10] bg-gradient-to-br from-[#d97706]/10 to-[#d97706]/5 rounded-2xl flex items-center justify-center mb-6 group-hover:from-[#d97706]/20 transition-all"><Globe className="w-12 h-12 text-[#d97706]/15"/></div><div className="flex items-center gap-4 mb-2"><span className="text-[9px] font-bold text-[#d97706] uppercase tracking-widest">{p.c}</span><span className="text-[9px] text-[#2a1f14]/20 uppercase tracking-widest">{p.loc}</span></div><h3 className="text-2xl font-black uppercase tracking-tighter group-hover:text-[#d97706] transition-colors mb-2">{p.t}</h3><p className="text-sm text-[#2a1f14]/30">{p.d}</p></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-white border-y border-[#2a1f14]/5"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter uppercase leading-[0.85] mb-24">How We <span className="text-[#d97706]">Help.</span></h2></Reveal><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-8">{SVC.map((f,i)=><Reveal key={i} delay={i*0.05}><div className="group p-10 bg-[#faf5f0] border border-[#2a1f14]/5 hover:border-[#d97706]/30 rounded-3xl transition-all"><div className="w-14 h-14 bg-[#d97706]/10 rounded-2xl flex items-center justify-center text-[#d97706] mb-8 group-hover:bg-[#d97706] group-hover:text-white transition-all">{f.icon}</div><h3 className="text-xl font-black uppercase tracking-tighter mb-4 group-hover:text-[#d97706] transition-colors">{f.t}</h3><p className="text-sm text-[#2a1f14]/40">{f.d}</p></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-[#faf5f0]"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter uppercase leading-[0.85] mb-24">Voices Of <span className="text-[#d97706]">Impact.</span></h2></Reveal><div className="grid grid-cols-1 md:grid-cols-3 gap-8">{TM.map((t,i)=><Reveal key={i} delay={i*0.1}><div className="p-10 bg-white border border-[#2a1f14]/5 rounded-3xl h-full flex flex-col"><div className="flex gap-1 mb-6">{[...Array(5)].map((_,j)=><Star key={j} className="w-4 h-4 text-[#d97706] fill-[#d97706]"/>)}</div><p className="text-base text-[#2a1f14]/50 italic leading-relaxed flex-1 mb-8">&ldquo;{t.q}&rdquo;</p><div className="pt-6 border-t border-[#2a1f14]/5"><div className="font-black uppercase text-sm">{t.n}</div><div className="text-[10px] text-[#2a1f14]/30 uppercase tracking-widest">{t.r}</div></div></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-[#2a1f14] text-white text-center"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-9xl font-black tracking-tighter uppercase mb-12">Give <span className="text-[#d97706]">Today.</span></h2><p className="max-w-xl mx-auto text-sm text-white/30 mb-16 uppercase tracking-widest italic">100% of your donation goes directly to the field.</p><div className="flex justify-center gap-4 flex-wrap">{["$25","$50","$100","$250"].map(a=><button key={a} className="px-10 py-5 border border-white/10 text-[12px] font-black uppercase tracking-widest hover:bg-[#d97706] hover:border-[#d97706] transition-all">{a}</button>)}</div></Reveal></div></section>

    <footer className="bg-[#2a1f14] border-t border-white/5 py-32 px-6 md:px-12 text-white"><div className="max-w-[1500px] mx-auto grid grid-cols-1 md:grid-cols-4 gap-24"><div className="col-span-1 md:col-span-2"><Link href="/" className="flex items-center gap-3 text-xl font-black tracking-tighter mb-10"><div className="w-8 h-8 bg-[#d97706] text-white rounded-full flex items-center justify-center"><Heart className="w-4 h-4"/></div><span>ESSENTIAL // GIVING</span></Link><p className="text-[11px] text-white/15 uppercase tracking-[0.2em] max-w-sm italic">Transparent philanthropy since 2018.</p></div><div><h4 className="text-[10px] font-black uppercase tracking-widest mb-10 text-[#d97706]">Programs</h4><ul className="space-y-5 text-[10px] font-bold text-white/20 uppercase tracking-widest">{["Water","Education","Health"].map(l=><li key={l}><Link href="#">{l}</Link></li>)}</ul></div><div><h4 className="text-[10px] font-black uppercase tracking-widest mb-10 text-[#d97706]">Connect</h4><ul className="space-y-5 text-[10px] font-bold text-white/20 uppercase tracking-widest">{["About","Volunteer","Contact"].map(l=><li key={l}><Link href="#">{l}</Link></li>)}</ul></div></div><div className="max-w-[1500px] mx-auto mt-32 pt-16 border-t border-white/5 text-center text-[9px] font-bold text-white/10 uppercase tracking-widest">&copy; 2026 ESSENTIAL GIVING</div></footer>
  </div>);
}
