"use client";
import { motion, useInView, AnimatePresence } from "framer-motion";
import { useState, useRef, useEffect } from "react";
import Link from "next/link";
import { Sparkles, Shield, Clock, Menu, X, Star, CheckCircle2, Home, Droplets, Leaf } from "lucide-react";
import "../premium.css";
const SVC=[{icon:<Home className="w-6 h-6"/>,t:"Deep Home Clean",d:"Top-to-bottom sanitization for every room."},{icon:<Sparkles className="w-6 h-6"/>,t:"Regular Upkeep",d:"Weekly or bi-weekly visits to keep your home spotless."},{icon:<Droplets className="w-6 h-6"/>,t:"Carpet & Upholstery",d:"Professional steam cleaning for lasting freshness."},{icon:<Shield className="w-6 h-6"/>,t:"Move-In/Out Clean",d:"Complete preparation for new tenants or owners."},{icon:<Leaf className="w-6 h-6"/>,t:"Eco-Friendly",d:"All-natural, non-toxic products safe for families."},{icon:<Clock className="w-6 h-6"/>,t:"Same-Day Service",d:"Book by noon, cleaned by evening. Guaranteed."}];
const TM=[{n:"Marie Laurent",r:"Homeowner",q:"My apartment has never looked this good. They're incredibly thorough and always on time."},{n:"David Kim",r:"Property Manager",q:"We use Essential for all 40 of our units. Consistent quality every single time."},{n:"Sophie Chen",r:"Working Mom",q:"Coming home to a sparkling clean house after a long day is absolutely priceless."}];
const PR=[{n:"BASIC",p:"$89",pd:"/visit",f:["2 bedrooms","1 bathroom","Kitchen & living","2h duration"],c:"Book_Now"},{n:"PREMIUM",p:"$149",pd:"/visit",f:["4 bedrooms","2 bathrooms","Full house","Appliances","Eco products"],c:"Book_Now",ft:true},{n:"CUSTOM",p:"From $199",pd:"",f:["Any size home","Deep sanitize","Carpet cleaning","Move-in/out","Priority scheduling"],c:"Get_Quote"}];
function Reveal({children,delay=0}:{children:React.ReactNode;delay?:number}){const ref=useRef(null);const iv=useInView(ref,{once:true,margin:"-50px"});return<motion.div ref={ref} initial={{opacity:0,y:20}} animate={iv?{opacity:1,y:0}:{}} transition={{duration:0.8,delay}}>{children}</motion.div>;}
export default function EssentialCleaningPage(){
  const[s,setS]=useState(false);const[m,setM]=useState(false);const[zip,setZip]=useState("");
  useEffect(()=>{const h=()=>setS(window.scrollY>50);window.addEventListener("scroll",h);return()=>window.removeEventListener("scroll",h);},[]);
  return(<div className="premium-theme min-h-screen bg-[#f0faf5] text-[#0f2419] font-mono selection:bg-[#10b981] selection:text-white overflow-x-hidden">
    <nav className={`fixed top-0 left-0 w-full z-50 transition-all duration-500 ${s?"bg-[#f0faf5]/90 backdrop-blur-xl py-4 border-b border-[#0f2419]/5":"bg-transparent py-10"}`}><div className="max-w-[1500px] mx-auto px-6 md:px-12 flex items-center justify-between"><Link href="/" className="group flex items-center gap-3 text-xl font-black tracking-tighter"><div className="w-8 h-8 bg-[#10b981] rounded-full flex items-center justify-center text-white"><Sparkles className="w-4 h-4"/></div><span className="group-hover:text-[#10b981] transition-colors">ESSENTIAL // <span className="text-[#0f2419]/30">CLEAN</span></span></Link><div className="hidden lg:flex items-center gap-10 text-[10px] font-bold uppercase tracking-[0.3em] text-[#0f2419]/30">{["Services","Pricing","About","Contact"].map(l=><Link key={l} href="#" className="hover:text-[#10b981] transition-colors">{l}</Link>)}</div><button className="px-6 py-2.5 bg-[#10b981] text-white text-[10px] font-black uppercase tracking-widest hover:bg-[#0f2419] transition-all hidden md:block">Book_Now</button><button onClick={()=>setM(true)} className="lg:hidden"><Menu className="w-6 h-6"/></button></div></nav>
    <AnimatePresence>{m&&(<motion.div initial={{opacity:0,x:"100%"}} animate={{opacity:1,x:0}} exit={{opacity:0,x:"100%"}} className="fixed inset-0 z-[100] bg-[#f0faf5] p-8 flex flex-col pt-32"><button onClick={()=>setM(false)} className="absolute top-10 right-8"><X className="w-10 h-10"/></button>{["Services","Pricing","About","Contact"].map(l=><Link key={l} href="#" onClick={()=>setM(false)} className="text-5xl font-black tracking-tighter uppercase mb-10">{l}</Link>)}</motion.div>)}</AnimatePresence>

    <section className="relative min-h-screen flex flex-col justify-center pt-20"><div className="max-w-[1500px] mx-auto px-6 md:px-12 relative z-10"><Reveal><div className="px-3 py-1 bg-[#10b981]/10 border border-[#10b981]/30 text-[#10b981] text-[9px] font-bold uppercase tracking-widest inline-block mb-8">TRUSTED_BY_2000+_HOMES</div><h1 className="text-7xl md:text-9xl lg:text-[10rem] font-black leading-[0.8] tracking-tighter uppercase mb-10">A Clean<br/>Home,<br/><span className="text-[#10b981]">Always.</span></h1><p className="max-w-xl text-lg text-[#0f2419]/40 leading-relaxed font-light uppercase tracking-widest italic mb-12">Professional eco-friendly cleaning services. Book in 30 seconds.</p><div className="flex flex-col sm:flex-row gap-4 max-w-lg"><input type="text" placeholder="Enter your ZIP code" value={zip} onChange={e=>setZip(e.target.value)} className="flex-1 px-6 py-5 bg-white border border-[#0f2419]/10 rounded-xl text-sm font-mono focus:border-[#10b981] focus:outline-none"/><button className="px-10 py-5 bg-[#10b981] text-white text-[10px] font-black uppercase tracking-[0.4em] hover:bg-[#0f2419] transition-all rounded-xl">Check_Area</button></div></Reveal></div></section>

    <section className="py-40 bg-white border-y border-[#0f2419]/5"><div className="max-w-[1500px] mx-auto px-6 md:px-12 grid grid-cols-1 lg:grid-cols-2 gap-24 items-center"><Reveal><span className="text-[10px] text-[#10b981] font-bold uppercase tracking-[0.4em] mb-6 block">About</span><h2 className="text-5xl md:text-7xl font-black tracking-tighter leading-[0.85] mb-8 uppercase">Spotless <span className="text-[#10b981]">Standards.</span></h2><p className="text-base text-[#0f2419]/40 leading-relaxed mb-12">Essential Cleaning was founded with one mission: make professional cleaning accessible, reliable, and eco-conscious. Every cleaner is vetted, trained, and insured.</p><div className="flex gap-16">{[{v:"2K+",l:"HOMES"},{v:"4.9★",l:"RATING"},{v:"100%",l:"ECO"}].map((s,i)=><div key={i}><div className="text-3xl font-black text-[#10b981]">{s.v}</div><div className="text-[9px] font-bold text-[#0f2419]/20 uppercase tracking-widest">{s.l}</div></div>)}</div></Reveal><Reveal delay={0.15}><div className="w-full aspect-square bg-gradient-to-br from-[#10b981]/10 to-[#10b981]/5 rounded-3xl flex items-center justify-center"><Sparkles className="w-20 h-20 text-[#10b981]/15"/></div></Reveal></div></section>

    <section className="py-40 bg-[#f0faf5]"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter uppercase leading-[0.85] mb-24">Our <span className="text-[#10b981]">Services.</span></h2></Reveal><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-8">{SVC.map((f,i)=><Reveal key={i} delay={i*0.05}><div className="group p-10 bg-white border border-[#0f2419]/5 hover:border-[#10b981]/30 rounded-3xl transition-all"><div className="w-14 h-14 bg-[#10b981]/10 rounded-2xl flex items-center justify-center text-[#10b981] mb-8 group-hover:bg-[#10b981] group-hover:text-white transition-all">{f.icon}</div><h3 className="text-xl font-black uppercase tracking-tighter mb-4 group-hover:text-[#10b981] transition-colors">{f.t}</h3><p className="text-sm text-[#0f2419]/40">{f.d}</p></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-white border-y border-[#0f2419]/5"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter uppercase leading-[0.85] mb-24">Happy <span className="text-[#10b981]">Homes.</span></h2></Reveal><div className="grid grid-cols-1 md:grid-cols-3 gap-8">{TM.map((t,i)=><Reveal key={i} delay={i*0.1}><div className="p-10 bg-[#f0faf5] border border-[#0f2419]/5 rounded-3xl h-full flex flex-col"><div className="flex gap-1 mb-6">{[...Array(5)].map((_,j)=><Star key={j} className="w-4 h-4 text-[#10b981] fill-[#10b981]"/>)}</div><p className="text-base text-[#0f2419]/50 italic leading-relaxed flex-1 mb-8">&ldquo;{t.q}&rdquo;</p><div className="pt-6 border-t border-[#0f2419]/5"><div className="font-black uppercase text-sm">{t.n}</div><div className="text-[10px] text-[#0f2419]/30 uppercase tracking-widest">{t.r}</div></div></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-[#f0faf5]"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter leading-[0.85] mb-24 uppercase text-center">Simple <span className="text-[#10b981]">Pricing.</span></h2></Reveal><div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl mx-auto">{PR.map((p,i)=><Reveal key={i} delay={i*0.1}><div className={`group p-10 border rounded-3xl transition-all ${p.ft?"bg-[#10b981]/5 border-[#10b981]/30 scale-105":"bg-white border-[#0f2419]/5"}`}><div className="text-[9px] font-bold text-[#10b981] uppercase tracking-widest mb-2">{p.n}</div><div className="text-4xl font-black mb-1">{p.p}<span className="text-lg text-[#0f2419]/30">{p.pd}</span></div><div className="space-y-4 mt-8 pt-8 border-t border-[#0f2419]/5">{p.f.map((f,j)=><div key={j} className="flex items-center gap-3 text-[10px] text-[#0f2419]/50"><CheckCircle2 className="w-3.5 h-3.5 text-[#10b981]"/>{f}</div>)}</div><button className={`mt-8 w-full py-3 text-[10px] font-black uppercase tracking-widest transition-all rounded-lg ${p.ft?"bg-[#10b981] text-white":"border border-[#0f2419]/10 hover:bg-[#10b981] hover:text-white"}`}>{p.c}</button></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-[#0f2419] text-white text-center"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-9xl font-black tracking-tighter uppercase mb-12">Book A <span className="text-[#10b981]">Clean.</span></h2><p className="max-w-xl mx-auto text-sm text-white/30 mb-16 uppercase tracking-widest italic">Your first clean is 20% off. No commitment required.</p><button className="px-16 py-6 bg-[#10b981] text-white text-[12px] font-black uppercase tracking-[0.4em] hover:bg-white hover:text-[#0f2419] transition-all">Get_Started</button></Reveal></div></section>

    <footer className="bg-[#0f2419] border-t border-white/5 py-32 px-6 md:px-12 text-white"><div className="max-w-[1500px] mx-auto grid grid-cols-1 md:grid-cols-4 gap-24"><div className="col-span-1 md:col-span-2"><Link href="/" className="flex items-center gap-3 text-xl font-black tracking-tighter mb-10"><div className="w-8 h-8 bg-[#10b981] text-white rounded-full flex items-center justify-center"><Sparkles className="w-4 h-4"/></div><span>ESSENTIAL // CLEAN</span></Link><p className="text-[11px] text-white/15 uppercase tracking-[0.2em] max-w-sm italic">Eco-friendly professional cleaning.</p></div><div><h4 className="text-[10px] font-black uppercase tracking-widest mb-10 text-[#10b981]">Services</h4><ul className="space-y-5 text-[10px] font-bold text-white/20 uppercase tracking-widest">{["Home","Office","Move-Out"].map(l=><li key={l}><Link href="#">{l}</Link></li>)}</ul></div><div><h4 className="text-[10px] font-black uppercase tracking-widest mb-10 text-[#10b981]">Company</h4><ul className="space-y-5 text-[10px] font-bold text-white/20 uppercase tracking-widest">{["About","Careers","Contact"].map(l=><li key={l}><Link href="#">{l}</Link></li>)}</ul></div></div><div className="max-w-[1500px] mx-auto mt-32 pt-16 border-t border-white/5 text-center text-[9px] font-bold text-white/10 uppercase tracking-widest">&copy; 2026 ESSENTIAL CLEANING</div></footer>
  </div>);
}
