"use client";
import { motion, useInView, AnimatePresence } from "framer-motion";
import { useState, useRef, useEffect } from "react";
import Link from "next/link";
import { Mic, Headphones, Play, Menu, X, Star, CheckCircle2, Radio, Volume2, Clock } from "lucide-react";
import "../premium.css";
const EPS=[{t:"The AI Safety Paradox",g:"Dr. Sarah Chen",d:"42 min"},{t:"Building in Public",g:"Marcus Rivera",d:"38 min"},{t:"Quantum Computing 2026",g:"Prof. Yuki Tanaka",d:"55 min"},{t:"Open Source Economics",g:"Emma Larsson",d:"44 min"}];
const FEAT=[{icon:<Mic className="w-6 h-6"/>,t:"Weekly Episodes",d:"New deep-dive conversations every Thursday morning."},{icon:<Headphones className="w-6 h-6"/>,t:"Ad-Free Listening",d:"Premium subscribers get zero interruptions."},{icon:<Radio className="w-6 h-6"/>,t:"Live Q&A Sessions",d:"Monthly live recordings with audience participation."},{icon:<Volume2 className="w-6 h-6"/>,t:"Exclusive Bonus",d:"Extended interviews and behind-the-scenes content."},{icon:<Clock className="w-6 h-6"/>,t:"Full Archive",d:"Access 200+ episodes from our complete back catalog."},{icon:<Play className="w-6 h-6"/>,t:"Multi-Platform",d:"Available on Spotify, Apple, YouTube, and RSS."}];
const TM=[{n:"Alex Kim",r:"Tech Lead",q:"Essential Podcast is my go-to for staying sharp on emerging tech."},{n:"Maria Santos",r:"Founder",q:"The depth of conversation here is unmatched. Every episode teaches me something."},{n:"David Park",r:"Developer",q:"I've listened to every episode twice. The quantum computing series was incredible."}];
const PR=[{n:"FREE",p:"$0",pd:"/mo",f:["Weekly episodes","Standard audio","Community Discord"],c:"Listen_Free"},{n:"PRO",p:"$9",pd:"/mo",f:["Ad-free","Bonus content","Live Q&A","Early access","HD audio"],c:"Go_Pro",ft:true},{n:"TEAM",p:"$29",pd:"/mo",f:["5 seats","Team discussions","Guest nominations","API access"],c:"Start_Team"}];
function Reveal({children,delay=0}:{children:React.ReactNode;delay?:number}){const ref=useRef(null);const iv=useInView(ref,{once:true,margin:"-50px"});return<motion.div ref={ref} initial={{opacity:0,y:20}} animate={iv?{opacity:1,y:0}:{}} transition={{duration:0.8,delay}}>{children}</motion.div>;}
export default function EssentialPodcastPage(){
  const[s,setS]=useState(false);const[m,setM]=useState(false);
  useEffect(()=>{const h=()=>setS(window.scrollY>50);window.addEventListener("scroll",h);return()=>window.removeEventListener("scroll",h);},[]);
  return(<div className="premium-theme min-h-screen bg-[#0a0a0f] text-white font-mono selection:bg-[#8b5cf6] selection:text-white overflow-x-hidden">
    <div className="fixed inset-0 pointer-events-none z-0"><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_50%_0%,#8b5cf615_0%,transparent_50%)]"/></div>
    <nav className={`fixed top-0 left-0 w-full z-50 transition-all duration-500 ${s?"bg-[#0a0a0f]/90 backdrop-blur-xl py-4 border-b border-white/5":"bg-transparent py-10"}`}><div className="max-w-[1500px] mx-auto px-6 md:px-12 flex items-center justify-between"><Link href="/" className="group flex items-center gap-3 text-xl font-black tracking-tighter"><div className="w-8 h-8 bg-[#8b5cf6] rounded-full flex items-center justify-center text-white"><Mic className="w-4 h-4"/></div><span className="group-hover:text-[#8b5cf6] transition-colors">ESSENTIAL // <span className="text-white/30">PODCAST</span></span></Link><div className="hidden lg:flex items-center gap-10 text-[10px] font-bold uppercase tracking-[0.3em] text-white/30">{["Episodes","Features","Pricing","Subscribe"].map(l=><Link key={l} href="#" className="hover:text-[#8b5cf6] transition-colors">{l}</Link>)}</div><button className="px-6 py-2.5 bg-[#8b5cf6] text-white text-[10px] font-black uppercase tracking-widest hover:bg-white hover:text-black transition-all hidden md:block">Subscribe</button><button onClick={()=>setM(true)} className="lg:hidden"><Menu className="w-6 h-6"/></button></div></nav>
    <AnimatePresence>{m&&(<motion.div initial={{opacity:0,x:"100%"}} animate={{opacity:1,x:0}} exit={{opacity:0,x:"100%"}} className="fixed inset-0 z-[100] bg-[#0a0a0f] p-8 flex flex-col pt-32"><button onClick={()=>setM(false)} className="absolute top-10 right-8"><X className="w-10 h-10"/></button>{["Episodes","Features","Pricing","Subscribe"].map(l=><Link key={l} href="#" onClick={()=>setM(false)} className="text-5xl font-black tracking-tighter uppercase mb-10">{l}</Link>)}</motion.div>)}</AnimatePresence>
    <section className="relative min-h-screen flex flex-col justify-center pt-20"><div className="max-w-[1500px] mx-auto px-6 md:px-12 relative z-10"><Reveal><div className="px-3 py-1 bg-[#8b5cf6]/10 border border-[#8b5cf6]/30 text-[#8b5cf6] text-[9px] font-bold uppercase tracking-widest inline-block mb-8">NEW_EPISODE_WEEKLY</div><h1 className="text-7xl md:text-9xl lg:text-[10rem] font-black leading-[0.8] tracking-tighter uppercase mb-10">Listen.<br/>Learn.<br/><span className="text-[#8b5cf6]">Lead.</span></h1><p className="max-w-xl text-lg text-white/30 leading-relaxed font-light uppercase tracking-widest italic mb-12">Deep conversations with the builders shaping tomorrow&apos;s technology.</p><div className="flex flex-col sm:flex-row gap-6"><button className="px-12 py-5 bg-[#8b5cf6] text-white text-[10px] font-black uppercase tracking-[0.4em] hover:bg-white hover:text-black transition-all">Latest_Episode</button><button className="px-12 py-5 border border-white/10 text-[10px] font-black uppercase tracking-[0.4em] hover:bg-white hover:text-black transition-all">Browse_All</button></div></Reveal></div></section>

    <section className="py-40 bg-[#0c0c14] border-y border-white/5"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter uppercase leading-[0.85] mb-24">Latest <span className="text-[#8b5cf6]">Episodes.</span></h2></Reveal><div className="space-y-4">{EPS.map((e,i)=><Reveal key={i} delay={i*0.05}><div className="group flex items-center justify-between p-8 bg-[#0e0e18] border border-white/5 hover:border-[#8b5cf6]/30 rounded-2xl transition-all cursor-pointer"><div className="flex items-center gap-6"><div className="w-12 h-12 bg-[#8b5cf6]/10 rounded-xl flex items-center justify-center text-[#8b5cf6] group-hover:bg-[#8b5cf6] group-hover:text-white transition-all"><Play className="w-5 h-5"/></div><div><h3 className="text-lg font-black uppercase tracking-tighter group-hover:text-[#8b5cf6] transition-colors">{e.t}</h3><div className="text-[10px] text-white/30 uppercase tracking-widest">{e.g}</div></div></div><div className="text-[10px] text-white/20 uppercase tracking-widest hidden md:block">{e.d}</div></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-[#0a0a0f]"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter uppercase leading-[0.85] mb-24">Why <span className="text-[#8b5cf6]">Listen.</span></h2></Reveal><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-8">{FEAT.map((f,i)=><Reveal key={i} delay={i*0.05}><div className="group p-10 bg-[#0c0c14] border border-white/5 hover:border-[#8b5cf6]/30 rounded-3xl transition-all"><div className="w-14 h-14 bg-white/5 rounded-2xl flex items-center justify-center text-[#8b5cf6] mb-8 group-hover:bg-[#8b5cf6] group-hover:text-white transition-all">{f.icon}</div><h3 className="text-xl font-black uppercase tracking-tighter mb-4 group-hover:text-[#8b5cf6] transition-colors">{f.t}</h3><p className="text-sm text-white/30">{f.d}</p></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-[#0c0c14] border-y border-white/5"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter uppercase leading-[0.85] mb-24">Listener <span className="text-[#8b5cf6]">Love.</span></h2></Reveal><div className="grid grid-cols-1 md:grid-cols-3 gap-8">{TM.map((t,i)=><Reveal key={i} delay={i*0.1}><div className="p-10 bg-[#0e0e18] border border-white/5 rounded-3xl h-full flex flex-col"><div className="flex gap-1 mb-6">{[...Array(5)].map((_,j)=><Star key={j} className="w-4 h-4 text-[#8b5cf6] fill-[#8b5cf6]"/>)}</div><p className="text-base text-white/40 italic leading-relaxed flex-1 mb-8">&ldquo;{t.q}&rdquo;</p><div className="pt-6 border-t border-white/5"><div className="font-black uppercase text-sm">{t.n}</div><div className="text-[10px] text-white/20 uppercase tracking-widest">{t.r}</div></div></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-[#0a0a0f]"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter leading-[0.85] mb-24 uppercase text-center">Simple <span className="text-[#8b5cf6]">Plans.</span></h2></Reveal><div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl mx-auto">{PR.map((p,i)=><Reveal key={i} delay={i*0.1}><div className={`group p-10 border rounded-3xl transition-all ${p.ft?"bg-[#8b5cf6]/5 border-[#8b5cf6]/30 scale-105":"bg-[#0c0c14] border-white/5"}`}><div className="text-[9px] font-bold text-[#8b5cf6] uppercase tracking-widest mb-2">{p.n}</div><div className="text-4xl font-black mb-1">{p.p}<span className="text-lg text-white/30">{p.pd}</span></div><div className="space-y-4 mt-8 pt-8 border-t border-white/5">{p.f.map((f,j)=><div key={j} className="flex items-center gap-3 text-[10px] text-white/40"><CheckCircle2 className="w-3.5 h-3.5 text-[#8b5cf6]"/>{f}</div>)}</div><button className={`mt-8 w-full py-3 text-[10px] font-black uppercase tracking-widest transition-all rounded-lg ${p.ft?"bg-[#8b5cf6] text-white":"border border-white/10 hover:bg-[#8b5cf6] hover:text-white"}`}>{p.c}</button></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-[#0c0c14] text-center border-t border-white/5"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-9xl font-black tracking-tighter uppercase mb-12">Start <span className="text-[#8b5cf6]">Listening.</span></h2><button className="px-16 py-6 bg-[#8b5cf6] text-white text-[12px] font-black uppercase tracking-[0.4em] hover:bg-white hover:text-black transition-all">Subscribe_Now</button></Reveal></div></section>

    <footer className="bg-[#0a0a0f] border-t border-white/5 py-32 px-6 md:px-12"><div className="max-w-[1500px] mx-auto grid grid-cols-1 md:grid-cols-4 gap-24"><div className="col-span-1 md:col-span-2"><Link href="/" className="flex items-center gap-3 text-xl font-black tracking-tighter mb-10"><div className="w-8 h-8 bg-[#8b5cf6] text-white rounded-full flex items-center justify-center"><Mic className="w-4 h-4"/></div><span>ESSENTIAL // PODCAST</span></Link><p className="text-[11px] text-white/15 uppercase tracking-[0.2em] max-w-sm italic">Deep tech conversations. Weekly.</p></div><div><h4 className="text-[10px] font-black uppercase tracking-widest mb-10 text-[#8b5cf6]">Listen</h4><ul className="space-y-5 text-[10px] font-bold text-white/20 uppercase tracking-widest">{["Episodes","Spotify","Apple"].map(l=><li key={l}><Link href="#">{l}</Link></li>)}</ul></div><div><h4 className="text-[10px] font-black uppercase tracking-widest mb-10 text-[#8b5cf6]">Connect</h4><ul className="space-y-5 text-[10px] font-bold text-white/20 uppercase tracking-widest">{["Twitter","Discord","Contact"].map(l=><li key={l}><Link href="#">{l}</Link></li>)}</ul></div></div><div className="max-w-[1500px] mx-auto mt-32 pt-16 border-t border-white/5 text-center text-[9px] font-bold text-white/10 uppercase tracking-widest">&copy; 2026 ESSENTIAL PODCAST</div></footer>
  </div>);
}
