"use client";
import { motion, useInView, AnimatePresence } from "framer-motion";
import { useState, useRef, useEffect } from "react";
import Link from "next/link";
import { Scissors, Star as StarIcon, Clock, Menu, X, Star, CheckCircle2, Users, Sparkles, Calendar } from "lucide-react";
import "../premium.css";
const SVC=[{icon:<Scissors className="w-6 h-6"/>,t:"Classic Cut",d:"Precision scissor or clipper cut with hot towel finish.",p:"$45"},{icon:<Sparkles className="w-6 h-6"/>,t:"Beard Sculpt",d:"Shape, trim, and condition with premium oils.",p:"$35"},{icon:<StarIcon className="w-6 h-6"/>,t:"Royal Package",d:"Cut, beard, facial, and scalp massage.",p:"$85"},{icon:<Users className="w-6 h-6"/>,t:"Kids Cut",d:"Patient, fun cuts for children under 12.",p:"$25"},{icon:<Calendar className="w-6 h-6"/>,t:"Hot Towel Shave",d:"Traditional straight-razor shave with steam.",p:"$40"},{icon:<Clock className="w-6 h-6"/>,t:"Express Trim",d:"Quick 15-minute shape-up between appointments.",p:"$20"}];
const TM=[{n:"Marcus Johnson",r:"Regular Client",q:"Best barbershop in the city. Been coming for 3 years and never had a bad cut."},{n:"Alex Rivera",r:"Groom, Wedding",q:"They handled my entire wedding party. Everyone looked incredible."},{n:"Tom Chen",r:"Monthly Regular",q:"The hot towel shave is an experience. You leave feeling like a new person."}];
function Reveal({children,delay=0}:{children:React.ReactNode;delay?:number}){const ref=useRef(null);const iv=useInView(ref,{once:true,margin:"-50px"});return<motion.div ref={ref} initial={{opacity:0,y:20}} animate={iv?{opacity:1,y:0}:{}} transition={{duration:0.8,delay}}>{children}</motion.div>;}
export default function EssentialSalonPage(){
  const[s,setS]=useState(false);const[m,setM]=useState(false);
  useEffect(()=>{const h=()=>setS(window.scrollY>50);window.addEventListener("scroll",h);return()=>window.removeEventListener("scroll",h);},[]);
  return(<div className="premium-theme min-h-screen bg-[#0a0a0a] text-white font-mono selection:bg-[#c8956c] selection:text-black overflow-x-hidden">
    <div className="fixed inset-0 pointer-events-none z-0"><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_30%_20%,#c8956c10_0%,transparent_50%)]"/></div>
    <nav className={`fixed top-0 left-0 w-full z-50 transition-all duration-500 ${s?"bg-[#0a0a0a]/90 backdrop-blur-xl py-4 border-b border-white/5":"bg-transparent py-10"}`}><div className="max-w-[1500px] mx-auto px-6 md:px-12 flex items-center justify-between"><Link href="/" className="group flex items-center gap-3 text-xl font-black tracking-tighter"><div className="w-8 h-8 bg-[#c8956c] rounded-sm flex items-center justify-center text-white"><Scissors className="w-4 h-4"/></div><span className="group-hover:text-[#c8956c] transition-colors">ESSENTIAL // <span className="text-white/30">SALON</span></span></Link><div className="hidden lg:flex items-center gap-10 text-[10px] font-bold uppercase tracking-[0.3em] text-white/30">{["Services","Pricing","About","Book"].map(l=><Link key={l} href="#" className="hover:text-[#c8956c] transition-colors">{l}</Link>)}</div><button className="px-6 py-2.5 bg-[#c8956c] text-white text-[10px] font-black uppercase tracking-widest hover:bg-white hover:text-black transition-all hidden md:block">Book_Now</button><button onClick={()=>setM(true)} className="lg:hidden"><Menu className="w-6 h-6"/></button></div></nav>
    <AnimatePresence>{m&&(<motion.div initial={{opacity:0,x:"100%"}} animate={{opacity:1,x:0}} exit={{opacity:0,x:"100%"}} className="fixed inset-0 z-[100] bg-[#0a0a0a] p-8 flex flex-col pt-32"><button onClick={()=>setM(false)} className="absolute top-10 right-8"><X className="w-10 h-10"/></button>{["Services","Pricing","About","Book"].map(l=><Link key={l} href="#" onClick={()=>setM(false)} className="text-5xl font-black tracking-tighter uppercase mb-10">{l}</Link>)}</motion.div>)}</AnimatePresence>

    <section className="relative min-h-screen flex flex-col justify-center pt-20"><div className="max-w-[1500px] mx-auto px-6 md:px-12 relative z-10"><Reveal><div className="px-3 py-1 bg-[#c8956c]/10 border border-[#c8956c]/30 text-[#c8956c] text-[9px] font-bold uppercase tracking-widest inline-block mb-8">EST._2019</div><h1 className="text-7xl md:text-9xl lg:text-[10rem] font-black leading-[0.8] tracking-tighter uppercase mb-10">Look<br/>Sharp.<br/><span className="text-[#c8956c]">Always.</span></h1><p className="max-w-xl text-lg text-white/30 leading-relaxed font-light uppercase tracking-widest italic mb-12">Premium barbershop & grooming studio. Walk-ins welcome.</p><div className="flex flex-col sm:flex-row gap-6"><button className="px-12 py-5 bg-[#c8956c] text-white text-[10px] font-black uppercase tracking-[0.4em] hover:bg-white hover:text-black transition-all">Book_Appointment</button><button className="px-12 py-5 border border-white/10 text-[10px] font-black uppercase tracking-[0.4em] hover:bg-white hover:text-black transition-all">View_Services</button></div></Reveal></div></section>

    <section className="py-40 bg-[#0c0c0c] border-y border-white/5"><div className="max-w-[1500px] mx-auto px-6 md:px-12 grid grid-cols-1 lg:grid-cols-2 gap-24 items-center"><Reveal><span className="text-[10px] text-[#c8956c] font-bold uppercase tracking-[0.4em] mb-6 block">About</span><h2 className="text-5xl md:text-7xl font-black tracking-tighter leading-[0.85] mb-8 uppercase">Craft &<br/><span className="text-[#c8956c]">Tradition.</span></h2><p className="text-base text-white/30 leading-relaxed mb-12">Essential Salon blends old-school barbering craft with modern style. Every cut is a conversation, every shave is a ritual. Walk in looking good, leave looking great.</p><div className="flex gap-16">{[{v:"5K+",l:"CLIENTS"},{v:"4.9★",l:"RATING"},{v:"6",l:"BARBERS"}].map((s,i)=><div key={i}><div className="text-3xl font-black text-[#c8956c]">{s.v}</div><div className="text-[9px] font-bold text-white/15 uppercase tracking-widest">{s.l}</div></div>)}</div></Reveal><Reveal delay={0.15}><div className="w-full aspect-square bg-gradient-to-br from-[#c8956c]/10 to-transparent rounded-3xl flex items-center justify-center"><Scissors className="w-20 h-20 text-[#c8956c]/15"/></div></Reveal></div></section>

    <section className="py-40 bg-[#0a0a0a]"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter uppercase leading-[0.85] mb-24">Services & <span className="text-[#c8956c]">Prices.</span></h2></Reveal><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-8">{SVC.map((f,i)=><Reveal key={i} delay={i*0.05}><div className="group p-10 bg-[#0c0c0c] border border-white/5 hover:border-[#c8956c]/30 rounded-3xl transition-all"><div className="flex justify-between items-start mb-8"><div className="w-14 h-14 bg-white/5 rounded-2xl flex items-center justify-center text-[#c8956c] group-hover:bg-[#c8956c] group-hover:text-white transition-all">{f.icon}</div><div className="text-2xl font-black text-[#c8956c]">{f.p}</div></div><h3 className="text-xl font-black uppercase tracking-tighter mb-4 group-hover:text-[#c8956c] transition-colors">{f.t}</h3><p className="text-sm text-white/30">{f.d}</p></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-[#0c0c0c] border-y border-white/5"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter uppercase leading-[0.85] mb-24">Client <span className="text-[#c8956c]">Reviews.</span></h2></Reveal><div className="grid grid-cols-1 md:grid-cols-3 gap-8">{TM.map((t,i)=><Reveal key={i} delay={i*0.1}><div className="p-10 bg-[#111] border border-white/5 rounded-3xl h-full flex flex-col"><div className="flex gap-1 mb-6">{[...Array(5)].map((_,j)=><Star key={j} className="w-4 h-4 text-[#c8956c] fill-[#c8956c]"/>)}</div><p className="text-base text-white/40 italic leading-relaxed flex-1 mb-8">&ldquo;{t.q}&rdquo;</p><div className="pt-6 border-t border-white/5"><div className="font-black uppercase text-sm">{t.n}</div><div className="text-[10px] text-white/20 uppercase tracking-widest">{t.r}</div></div></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-[#0a0a0a] text-center"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-9xl font-black tracking-tighter uppercase mb-12">Book Your <span className="text-[#c8956c]">Cut.</span></h2><p className="max-w-xl mx-auto text-sm text-white/30 mb-16 uppercase tracking-widest italic">Walk-ins welcome. Online booking preferred.</p><button className="px-16 py-6 bg-[#c8956c] text-white text-[12px] font-black uppercase tracking-[0.4em] hover:bg-white hover:text-black transition-all">Reserve_Slot</button></Reveal></div></section>

    <footer className="bg-[#0a0a0a] border-t border-white/5 py-32 px-6 md:px-12"><div className="max-w-[1500px] mx-auto grid grid-cols-1 md:grid-cols-4 gap-24"><div className="col-span-1 md:col-span-2"><Link href="/" className="flex items-center gap-3 text-xl font-black tracking-tighter mb-10"><div className="w-8 h-8 bg-[#c8956c] text-white rounded-sm flex items-center justify-center"><Scissors className="w-4 h-4"/></div><span>ESSENTIAL // SALON</span></Link><p className="text-[11px] text-white/15 uppercase tracking-[0.2em] max-w-sm italic">Premium barbershop & grooming. Est. 2019.</p></div><div><h4 className="text-[10px] font-black uppercase tracking-widest mb-10 text-[#c8956c]">Hours</h4><ul className="space-y-5 text-[10px] font-bold text-white/20 uppercase tracking-widest"><li>Mon-Fri 9-8</li><li>Sat 9-6</li><li>Sun Closed</li></ul></div><div><h4 className="text-[10px] font-black uppercase tracking-widest mb-10 text-[#c8956c]">Contact</h4><ul className="space-y-5 text-[10px] font-bold text-white/20 uppercase tracking-widest">{["Instagram","Yelp","Call_Us"].map(l=><li key={l}><Link href="#">{l}</Link></li>)}</ul></div></div><div className="max-w-[1500px] mx-auto mt-32 pt-16 border-t border-white/5 text-center text-[9px] font-bold text-white/10 uppercase tracking-widest">&copy; 2026 ESSENTIAL SALON</div></footer>
  </div>);
}
