"use client";
import { motion, useInView, AnimatePresence } from "framer-motion";
import { useState, useRef, useEffect } from "react";
import Link from "next/link";
import { Building2, Leaf, TreePine, Menu, X, Star, CheckCircle2, Droplets, Sun, Recycle, Wind } from "lucide-react";
import "../premium.css";
const SVC=[{icon:<Leaf className="w-6 h-6"/>,t:"Biophilic Design",d:"Living systems integrated into architectural form."},{icon:<Sun className="w-6 h-6"/>,t:"Passive Energy",d:"Orientation and envelope optimized for zero-energy."},{icon:<Droplets className="w-6 h-6"/>,t:"Water Systems",d:"Rainwater harvest, greywater recycling, living filtration."},{icon:<Recycle className="w-6 h-6"/>,t:"Circular Materials",d:"Reclaimed, bio-based, cradle-to-cradle certified."},{icon:<Wind className="w-6 h-6"/>,t:"Natural Ventilation",d:"Stack effect replacing mechanical HVAC."},{icon:<TreePine className="w-6 h-6"/>,t:"Mass Timber",d:"Engineered wood structures sequestering carbon."}];
const PRJ=[{t:"Eden Tower",c:"RESIDENTIAL",l:"Copenhagen"},{t:"Solaris Pavilion",c:"PUBLIC",l:"Singapore"},{t:"Watershed HQ",c:"COMMERCIAL",l:"Portland"},{t:"Canopy School",c:"EDUCATION",l:"Nairobi"}];
const TM=[{n:"Dr. Ingrid Holm",r:"Mayor, Copenhagen",q:"Bio Form proved sustainable architecture can be the most beautiful."},{n:"Kenji Sato",r:"Developer",q:"Passive energy cut operating costs by 60% while winning design awards."},{n:"Amara Obi",r:"Director, Nairobi Schools",q:"The Canopy School changed how students experience learning."}];
function Reveal({children,delay=0}:{children:React.ReactNode;delay?:number}){const ref=useRef(null);const iv=useInView(ref,{once:true,margin:"-50px"});return<motion.div ref={ref} initial={{opacity:0,y:20}} animate={iv?{opacity:1,y:0}:{}} transition={{duration:0.8,delay}}>{children}</motion.div>;}
export default function BioFormArchPage(){
  const[scrolled,setScrolled]=useState(false);const[menuOpen,setMenuOpen]=useState(false);
  useEffect(()=>{const h=()=>setScrolled(window.scrollY>50);window.addEventListener("scroll",h);return()=>window.removeEventListener("scroll",h);},[]);
  const A="#588157",B="#f5f7f0",C="#1a2e1a";
  return(<div className="premium-theme min-h-screen bg-[#f5f7f0] text-[#1a2e1a] font-mono selection:bg-[#588157] selection:text-white overflow-x-hidden">
    <nav className={`fixed top-0 left-0 w-full z-50 transition-all duration-500 ${scrolled?"bg-[#f5f7f0]/90 backdrop-blur-xl py-4 border-b border-[#1a2e1a]/5":"bg-transparent py-10"}`}><div className="max-w-[1500px] mx-auto px-6 md:px-12 flex items-center justify-between"><Link href="/" className="group flex items-center gap-3 text-xl font-black tracking-tighter"><div className="w-8 h-8 bg-[#588157] rounded-full flex items-center justify-center text-white"><Building2 className="w-4 h-4"/></div><span className="group-hover:text-[#588157] transition-colors">BIO FORM // <span className="text-[#1a2e1a]/30">ARCH</span></span></Link><div className="hidden lg:flex items-center gap-10 text-[10px] font-bold uppercase tracking-[0.3em] text-[#1a2e1a]/30">{["Projects","Services","About","Contact"].map(l=><Link key={l} href="#" className="hover:text-[#588157] transition-colors">{l}</Link>)}</div><button className="px-6 py-2.5 bg-[#588157] text-white text-[10px] font-black uppercase tracking-widest hover:bg-[#1a2e1a] transition-all hidden md:block">Inquire</button><button onClick={()=>setMenuOpen(true)} className="lg:hidden"><Menu className="w-6 h-6"/></button></div></nav>
    <AnimatePresence>{menuOpen&&(<motion.div initial={{opacity:0,x:"100%"}} animate={{opacity:1,x:0}} exit={{opacity:0,x:"100%"}} className="fixed inset-0 z-[100] bg-[#f5f7f0] p-8 flex flex-col pt-32"><button onClick={()=>setMenuOpen(false)} className="absolute top-10 right-8"><X className="w-10 h-10"/></button>{["Projects","Services","About","Contact"].map(l=><Link key={l} href="#" onClick={()=>setMenuOpen(false)} className="text-5xl font-black tracking-tighter uppercase mb-10">{l}</Link>)}</motion.div>)}</AnimatePresence>

    <section className="relative min-h-screen flex flex-col justify-center pt-20"><div className="max-w-[1500px] mx-auto px-6 md:px-12 relative z-10"><Reveal><div className="px-3 py-1 bg-[#588157]/10 border border-[#588157]/30 text-[#588157] text-[9px] font-bold uppercase tracking-widest inline-block mb-8">LEED_PLATINUM</div><h1 className="text-7xl md:text-9xl lg:text-[10rem] font-black leading-[0.8] tracking-tighter uppercase mb-10">Build<br/>With<br/><span className="text-[#588157]">Nature.</span></h1><p className="max-w-xl text-lg text-[#1a2e1a]/40 leading-relaxed font-light uppercase tracking-widest italic mb-12">Sustainable architecture studio. Buildings that heal the planet.</p><div className="flex flex-col sm:flex-row gap-6"><button className="px-12 py-5 bg-[#588157] text-white text-[10px] font-black uppercase tracking-[0.4em] hover:bg-[#1a2e1a] transition-all">View_Projects</button><button className="px-12 py-5 border border-[#1a2e1a]/10 text-[10px] font-black uppercase tracking-[0.4em] hover:bg-[#1a2e1a] hover:text-white transition-all">Our_Approach</button></div></Reveal></div></section>

    <section className="py-40 bg-white border-y border-[#1a2e1a]/5"><div className="max-w-[1500px] mx-auto px-6 md:px-12 grid grid-cols-1 lg:grid-cols-2 gap-24 items-center"><Reveal><span className="text-[10px] text-[#588157] font-bold uppercase tracking-[0.4em] mb-6 block">About</span><h2 className="text-5xl md:text-7xl font-black tracking-tighter leading-[0.85] mb-8 uppercase">Architecture <span className="text-[#588157]">Alive.</span></h2><p className="text-base text-[#1a2e1a]/40 leading-relaxed mb-12">Founded in 2015, Bio Form Arch designs buildings that function as living ecosystems. Every project is carbon-negative and biophilically rich.</p><div className="flex gap-16">{[{v:"42",l:"PROJECTS"},{v:"100%",l:"LEED"},{v:"-2.4K",l:"TONS_CO2"}].map((s,i)=><div key={i}><div className="text-3xl font-black text-[#588157]">{s.v}</div><div className="text-[9px] font-bold text-[#1a2e1a]/20 uppercase tracking-widest">{s.l}</div></div>)}</div></Reveal><Reveal delay={0.15}><div className="w-full aspect-square bg-gradient-to-br from-[#588157]/10 to-[#588157]/5 rounded-3xl flex items-center justify-center"><TreePine className="w-20 h-20 text-[#588157]/15"/></div></Reveal></div></section>

    <section className="py-40 bg-[#f5f7f0]"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter uppercase leading-[0.85] mb-24">Selected <span className="text-[#588157]">Work.</span></h2></Reveal><div className="grid grid-cols-1 md:grid-cols-2 gap-8">{PRJ.map((p,i)=><Reveal key={i} delay={i*0.05}><div className="group cursor-pointer"><div className="w-full aspect-[16/10] bg-gradient-to-br from-[#588157]/10 to-[#588157]/5 rounded-2xl flex items-center justify-center mb-6 group-hover:from-[#588157]/20 transition-all"><Building2 className="w-12 h-12 text-[#588157]/15"/></div><span className="text-[9px] font-bold text-[#588157] uppercase tracking-widest">{p.c}</span><span className="text-[9px] text-[#1a2e1a]/20 uppercase tracking-widest ml-4">{p.l}</span><h3 className="text-2xl font-black uppercase tracking-tighter group-hover:text-[#588157] transition-colors">{p.t}</h3></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-white border-y border-[#1a2e1a]/5"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter uppercase leading-[0.85] mb-24">Our <span className="text-[#588157]">Services.</span></h2></Reveal><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-8">{SVC.map((s,i)=><Reveal key={i} delay={i*0.05}><div className="group p-10 bg-[#f5f7f0] border border-[#1a2e1a]/5 hover:border-[#588157]/30 rounded-3xl transition-all"><div className="w-14 h-14 bg-[#588157]/10 rounded-2xl flex items-center justify-center text-[#588157] mb-8 group-hover:bg-[#588157] group-hover:text-white transition-all">{s.icon}</div><h3 className="text-xl font-black uppercase tracking-tighter mb-4 group-hover:text-[#588157] transition-colors">{s.t}</h3><p className="text-sm text-[#1a2e1a]/40">{s.d}</p></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-[#f5f7f0]"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter uppercase leading-[0.85] mb-24">Client <span className="text-[#588157]">Words.</span></h2></Reveal><div className="grid grid-cols-1 md:grid-cols-3 gap-8">{TM.map((t,i)=><Reveal key={i} delay={i*0.1}><div className="p-10 bg-white border border-[#1a2e1a]/5 rounded-3xl h-full flex flex-col"><div className="flex gap-1 mb-6">{[...Array(5)].map((_,j)=><Star key={j} className="w-4 h-4 text-[#588157] fill-[#588157]"/>)}</div><p className="text-base text-[#1a2e1a]/50 italic leading-relaxed flex-1 mb-8">&ldquo;{t.q}&rdquo;</p><div className="pt-6 border-t border-[#1a2e1a]/5"><div className="font-black uppercase text-sm">{t.n}</div><div className="text-[10px] text-[#1a2e1a]/30 uppercase tracking-widest">{t.r}</div></div></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-[#1a2e1a] text-white text-center"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-9xl font-black tracking-tighter uppercase mb-12">Build <span className="text-[#588157]">Better.</span></h2><p className="max-w-xl mx-auto text-sm text-white/30 mb-16 uppercase tracking-widest italic">Ready to design a building that gives back?</p><button className="px-16 py-6 bg-[#588157] text-white text-[12px] font-black uppercase tracking-[0.4em] hover:bg-white hover:text-[#1a2e1a] transition-all">Start_Project</button></Reveal></div></section>

    <footer className="bg-[#1a2e1a] border-t border-white/5 py-32 px-6 md:px-12 text-white"><div className="max-w-[1500px] mx-auto grid grid-cols-1 md:grid-cols-4 gap-24"><div className="col-span-1 md:col-span-2"><Link href="/" className="flex items-center gap-3 text-xl font-black tracking-tighter mb-10"><div className="w-8 h-8 bg-[#588157] text-white rounded-full flex items-center justify-center"><Building2 className="w-4 h-4"/></div><span>BIO FORM // ARCH</span></Link><p className="text-[11px] text-white/15 uppercase tracking-[0.2em] max-w-sm italic">Sustainable architecture studio.</p></div><div><h4 className="text-[10px] font-black uppercase tracking-widest mb-10 text-[#588157]">Studio</h4><ul className="space-y-5 text-[10px] font-bold text-white/20 uppercase tracking-widest">{["Projects","Services","Process"].map(l=><li key={l}><Link href="#">{l}</Link></li>)}</ul></div><div><h4 className="text-[10px] font-black uppercase tracking-widest mb-10 text-[#588157]">Connect</h4><ul className="space-y-5 text-[10px] font-bold text-white/20 uppercase tracking-widest">{["Globe","LinkedIn","Contact"].map(l=><li key={l}><Link href="#">{l}</Link></li>)}</ul></div></div><div className="max-w-[1500px] mx-auto mt-32 pt-16 border-t border-white/5 text-center text-[9px] font-bold text-white/10 uppercase tracking-widest">&copy; 2026 BIO FORM ARCH</div></footer>
  </div>);
}