export interface TemplateMetadata {
  id: string;
  name: string;
  description: string;
  category: "Tech" | "Luxury" | "Editorial" | "Creative" | "Minimal" | "Free";
  style: "Dark" | "Light" | "Vibrant";
  tags: string[];
  tier: "Essentiel" | "Pro" | "Premium";
  sections: number;
}

export const TEMPLATES_REGISTRY: TemplateMetadata[] = [
  {
    id: "impact-01",
    name: "NOVA Agency",
    description: "Full multi-section agency vitrine with scroll animations, magnetic buttons, portfolio carousel, and contact form.",
    category: "Creative",
    style: "Dark",
    tags: ["Agency", "Vitrine", "Multi-Section", "Animated"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-02",
    name: "Elena Korr Portfolio",
    description: "Cinematic photographer portfolio with filterable masonry gallery, fullscreen project modals, and awards section.",
    category: "Creative",
    style: "Dark",
    tags: ["Portfolio", "Photography", "Masonry", "Modal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-03",
    name: "Maison Dorée",
    description: "Luxury e-commerce boutique with 3D tilt product cards, cart drawer, wishlist, lookbook gallery, and product detail views.",
    category: "Luxury",
    style: "Light",
    tags: ["E-commerce", "Luxury", "3D Tilt", "Cart"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-04",
    name: "L'Étoile Restaurant",
    description: "Fine dining restaurant vitrine with tabbed animated menu, reservation modal, ambiance gallery, and chef story section.",
    category: "Luxury",
    style: "Dark",
    tags: ["Restaurant", "Vitrine", "Menu", "Reservation"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-05",
    name: "NovaPlatform SaaS",
    description: "Modern SaaS landing with floating UI cards, feature grid, timeline, pricing toggle, testimonials, and conversion CTAs.",
    category: "Tech",
    style: "Dark",
    tags: ["SaaS", "Pricing", "Timeline", "Marketplace"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-06",
    name: "Neuralis",
    description: "Premium neuro-tech interface with real-time neural bridge diagnostics, biological integrity audits, and clinical trial data visualization.",
    category: "Tech",
    style: "Dark",
    tags: ["Neuro-Tech", "HUD", "Clinical", "Interactive"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-07",
    name: "Aether Sound",
    description: "Ultra-luxury high-fidelity audio boutique with acoustic engineering manifests, artisan luthier profiles, and heritage timelines.",
    category: "Luxury",
    style: "Dark",
    tags: ["Audio", "Hi-Fi", "Artisan", "Heritage"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-08",
    name: "Vulcan Motors",
    description: "Elite automotive atelier featuring hypercar performance manifests, aerodynamic logic audits, and bespoke 1-of-1 customization portals.",
    category: "Luxury",
    style: "Dark",
    tags: ["Automotive", "Hypercar", "Performance", "Bespoke"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-09",
    name: "Astrum Reach",
    description: "Premium orbital logistics & space tourism manifest with aerospace engineering schematics, mission command dossiers, and safety protocols.",
    category: "Tech",
    style: "Dark",
    tags: ["Aerospace", "Space", "Logistics", "Safety"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-10",
    name: "Veridian",
    description: "Ultra-luxury botanical atelier with rare terpene genealogies, organic cultivation manifests, and cold-cure laboratory audits.",
    category: "Luxury",
    style: "Dark",
    tags: ["Botanical", "Cannabis", "Organic", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-11",
    name: "Aether Visuals",
    description: "Premium architectural visualization & synthesis atelier featuring photorealistic spatial manifests and structural audits.",
    category: "Tech",
    style: "Dark",
    tags: ["Architecture", "Visualization", "CGI", "Synthesis"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-12",
    name: "ARCHIVE // STUDIO",
    description: "High-end brutalist creative agency SPA with massive typography, raw grids, and aesthetic research dossiers.",
    category: "Creative",
    style: "Dark",
    tags: ["Brutalist", "Agency", "Editorial", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-13",
    name: "CHRONOS // ATELIER",
    description: "Ultra-luxury horology & watchmaking boutique with precision mechanical manifests and heritage timelines.",
    category: "Luxury",
    style: "Dark",
    tags: ["Horology", "Watches", "Luxury", "Precision"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-14",
    name: "AETHEL // MARITIME",
    description: "Premium superyacht & maritime excellence SPA featuring fleet manifests and hydrodynamic engineering synthesis.",
    category: "Luxury",
    style: "Dark",
    tags: ["Maritime", "Yacht", "Luxury", "Engineering"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-15",
    name: "GHOST_SHELL // DEFENSE",
    description: "Premium cyber-defense & tactical operations SPA featuring network isolation vectors and kernel integrity logs.",
    category: "Tech",
    style: "Dark",
    tags: ["Cybersecurity", "Defense", "Tactical", "HUD"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-16",
    name: "LUMINA // ARCHIVE",
    description: "Premium atmospheric lighting & visual arts studio featuring photon manifests and neural optics research.",
    category: "Tech",
    style: "Dark",
    tags: ["Lighting", "Visual Arts", "Cinematic", "Atmospheric"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-17",
    name: "CONCRETE // ATELIER",
    description: "Premium brutalist architecture & masonry studio featuring structural manifests and robotic fabrication dossiers.",
    category: "Minimal",
    style: "Dark",
    tags: ["Brutalist", "Architecture", "Masonry", "Engineering"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-18",
    name: "FLUID // OS",
    description: "Premium creative tech & software interface studio featuring neural core modules and kinetic UI metrics.",
    category: "Creative",
    style: "Dark",
    tags: ["Software", "Interface", "OS", "Interactive"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-19",
    name: "AEVIA // AGENCY",
    description: "Premium venture equity & growth agency featuring venture manifests and alpha synthesis metrics.",
    category: "Corporate",
    style: "Light",
    tags: ["Venture Capital", "Growth", "Agency", "Alpha"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-20",
    name: "HERITAGE // GOLD",
    description: "Premium luxury jewelry & gold smithing atelier featuring high-jewelry manifests and ancestral lineage logs.",
    category: "Luxury",
    style: "Dark",
    tags: ["Jewelry", "Gold", "Luxury", "Heritage"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-21",
    name: "NEO // OBJECT",
    description: "Premium industrial design & object atelier featuring material manifests and forge dossiers.",
    category: "Minimal",
    style: "Light",
    tags: ["Industrial", "Minimal", "Product", "Forge"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-22",
    name: "SPLIT // OS",
    description: "Premium distributed tech & creative software platform featuring multi-column node manifests.",
    category: "Tech",
    style: "Dark",
    tags: ["Software", "Distributed", "OS", "Interactive"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-23",
    name: "NOIR // DIRECT",
    description: "Premium film production & cinematic creative studio featuring storyboard manifests and narrative logs.",
    category: "Creative",
    style: "Dark",
    tags: ["Cinema", "Film", "Production", "Studio"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-24",
    name: "ORBITAL // INDEX",
    description: "Premium high-growth startup accelerator & venture index featuring equity manifests and forge dossiers.",
    category: "Creative",
    style: "Dark",
    tags: ["Venture", "Accelerator", "Growth", "Index"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-25",
    name: "MAGNETIC // HUD",
    description: "Premium advanced analytics & intelligence platform featuring node manifests and real-time telemetry shells.",
    category: "Tech",
    style: "Dark",
    tags: ["HUD", "Interactive", "3D", "Intelligence"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-26",
    name: "GLASS // BOUTIQUE",
    description: "Premium Luxury Fragrance SPA featuring olfactory manifests, frosted forge dossiers, and molecular laboratory logs.",
    category: "Luxury",
    style: "Glass",
    tags: ["E-commerce", "Fragrance", "Premium", "SPA"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-27",
    name: "PERSPECTIVE // OS",
    description: "Premium Creative Interface SPA featuring interface manifests, layered 3D UI shells, and spatial telemetry logs.",
    category: "Creative",
    style: "3D",
    tags: ["Interface", "OS", "Platform", "SPA"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-28",
    name: "AETHER // ARCH",
    description: "Premium Brutalist Architecture SPA featuring structural manifests, monolithic forge dossiers, and material laboratory logs.",
    category: "Minimal",
    style: "Brutalist",
    tags: ["Architecture", "Brutalist", "Studio", "SPA"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-29",
    name: "GLITCH // INDEX",
    description: "Premium Technical Creative SPA featuring project manifests, grid-based interface shells, and code laboratory logs.",
    category: "Tech",
    style: "Glitch",
    tags: ["Portfolio", "Glitch", "Agency", "SPA"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-30",
    name: "MOUSETRAP // FX",
    description: "Premium Creative Interactive SPA featuring VFX manifests, kinetic interface shells, and physics laboratory logs.",
    category: "Creative",
    style: "Interactive",
    tags: ["VFX", "Interactive", "Special FX", "SPA"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-31",
    name: "LENS // STUDIO",
    description: "Fine art photography gallery with elegant framed reveals and archival manifests.",
    category: "Luxury",
    style: "Light",
    tags: ["Photography", "Gallery", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-32",
    name: "AEVIA // KITCHEN",
    description: "High-end gastronomy menu with fluid dish reveals and thermal laboratory logs.",
    category: "Luxury",
    style: "Dark",
    tags: ["Food", "Gastronomy", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-33",
    name: "WAVE // OS",
    description: "Quantum wavefront processing with interactive particle sine waves and spectral shells.",
    category: "Tech",
    style: "Dark",
    tags: ["Quantum", "Data", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-34",
    name: "HORIZON // ESTATES",
    description: "Cinematic real estate showcase with technical architectural HUDs and advisory dossiers.",
    category: "Minimal",
    style: "Light",
    tags: ["Real Estate", "Architecture", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-35",
    name: "FLIP // STUDIO",
    description: "Editorial fashion carousel with 3D flip magazine transitions and pattern manifests.",
    category: "Editorial",
    style: "Light",
    tags: ["Fashion", "Magazine", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-36",
    name: "MINIMAL // OBJECTS",
    description: "High-contrast minimalist e-commerce showcase with object manifests and tactile interface shells.",
    category: "Minimal",
    style: "Light",
    tags: ["E-commerce", "Minimal", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-37",
    name: "KINETIC // LENS",
    description: "Creative photography grid with scroll-linked vertical parallax and optic interface shells.",
    category: "Creative",
    style: "Dark",
    tags: ["Photography", "Kinetic", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-38",
    name: "ZEN // KITCHEN",
    description: "Japanese-inspired minimalist restaurant layout with dish manifests and culinary interface shells.",
    category: "Minimal",
    style: "Light",
    tags: ["Food", "Japanese", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-39",
    name: "BLUEPRINT // NODE",
    description: "Technical real estate visualization with architectural HUDs and spatial laboratory logs.",
    category: "Tech",
    style: "Dark",
    tags: ["Architecture", "HUD", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-40",
    name: "THE // JOURNEY",
    description: "Immersive storytelling experience with chapter-based navigation and narrative interface shells.",
    category: "Creative",
    style: "Dark",
    tags: ["Storytelling", "Cinematic", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-41",
    name: "DYNAMIC // LIVE",
    description: "Real-time broadcast HUD with broadcast manifests and signal interface shells.",
    category: "Tech",
    style: "Dark",
    tags: ["Broadcast", "HUD", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-42",
    name: "CLUSTER // OS",
    description: "Drifting asset cloud with asset manifests and spatial cloud interface shells.",
    category: "Creative",
    style: "Light",
    tags: ["Cloud", "Parallax", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-43",
    name: "FILM // UNIT",
    description: "Cinematic film production experience with scene manifests and anamorphic interface shells.",
    category: "Creative",
    style: "Dark",
    tags: ["Film", "Cinematic", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-44",
    name: "NEURAL // MESH",
    description: "Technical AI network interface with node manifests and network interface shells.",
    category: "Tech",
    style: "Dark",
    tags: ["AI", "Network", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-45",
    name: "SHOP // RING",
    description: "Luxury product carousel with product manifests and luxury interface shells.",
    category: "Luxury",
    style: "Dark",
    tags: ["Luxury", "Carousel", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-46",
    name: "GLITCH // CORE",
    description: "Technical glitch interface with core manifests and system interface shells.",
    category: "Tech",
    style: "Dark",
    tags: ["Glitch", "Technical", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-47",
    name: "DATA // STREAM",
    description: "Binary cascade interface with stream manifests and system interface shells.",
    category: "Tech",
    style: "Dark",
    tags: ["Data", "Cascade", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-48",
    name: "LENS // OPTIC",
    description: "Chromatic light interface with optic manifests and spectral interface shells.",
    category: "Tech",
    style: "Dark",
    tags: ["Light", "Optic", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-49",
    name: "FOLD // LOGIC",
    description: "3D paper folding interface with paper manifests and material interface shells.",
    category: "Creative",
    style: "Light",
    tags: ["Paper", "3D", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-50",
    name: "LIQUID // METAL",
    description: "Viscous fluid interface with liquid manifests and fluid interface shells.",
    category: "Tech",
    style: "Dark",
    tags: ["Fluid", "Metal", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-51",
    name: "LAYER // FX",
    description: "Multi-layered composition interface with layer manifests and system interface shells.",
    category: "Tech",
    style: "Dark",
    tags: ["Layer", "FX", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-52",
    name: "PARTICLE // FIELD",
    description: "Dynamic particle field interface with particle manifests and field interface shells.",
    category: "Tech",
    style: "Dark",
    tags: ["Particle", "Field", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-53",
    name: "MESH // WARP",
    description: "SVG mesh deformation interface with mesh manifests and warp interface shells.",
    category: "Tech",
    style: "Dark",
    tags: ["Mesh", "Warp", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-54",
    name: "ECHO // SCROLL",
    description: "Kinetic typography interface with echo manifests and scroll interface shells.",
    category: "Tech",
    style: "Dark",
    tags: ["Echo", "Scroll", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-55",
    name: "NEON // HUD",
    description: "Sci-Fi HUD interface with neon manifests and HUD interface shells.",
    category: "Tech",
    style: "Dark",
    tags: ["Neon", "HUD", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-56",
    name: "Split Slider",
    description: "Cinematic vertical split transitions for high-end narratives.",
    category: "Editorial",
    style: "Dark",
    tags: ["Slider", "Split", "Editorial"],
  },
  {
    id: "impact-57",
    name: "Mask Unit",
    description: "Large-scale typography with masked background video effects.",
    category: "Creative",
    style: "Light",
    tags: ["Hero", "Masking", "Creative"],
  },
  {
    id: "impact-58",
    name: "Skew OS",
    description: "Kinetic scroll carousel with dynamic skew distortion.",
    category: "Creative",
    style: "Dark",
    tags: ["Carousel", "Kinetic", "Perspective"],
  },
  {
    id: "impact-59",
    name: "Spec 059",
    description: "Technical e-commerce showcase with interactive spec highlighting.",
    category: "Tech",
    style: "Dark",
    tags: ["E-commerce", "Interactive", "HUD"],
  },
  {
    id: "impact-60",
    name: "Stack OS",
    description: "Brutalist photography stack with sticky reveal transitions.",
    category: "Minimal",
    style: "Light",
    tags: ["Photography", "Brutalist", "Gallery"],
  },
  {
    id: "impact-61",
    name: "Segment OS",
    description: "One-page vertical dot navigation with smooth snap segments.",
    category: "Minimal",
    style: "Light",
    tags: ["One-Page", "Navigation", "Minimal"],
  },
  {
    id: "impact-62",
    name: "Liquid OS",
    description: "Visceral 'Gooey' SVG filter transitions for bold typography.",
    category: "Creative",
    style: "Dark",
    tags: ["Typography", "Special FX", "Liquid"],
  },
  {
    id: "impact-63",
    name: "Orbit Unit",
    description: "Scroll-linked luxury product rotation and scaling.",
    category: "Luxury",
    style: "Light",
    tags: ["Luxury", "Parallax", "Product"],
  },
  {
    id: "impact-64",
    name: "Data Stream OS",
    description: "Modern Matrix-inspired data rain with technical code fragments.",
    category: "Tech",
    style: "Dark",
    tags: ["Tech", "Particle Effects", "Matrix"],
  },
  {
    id: "impact-65",
    name: "Complex OS",
    description: "Complex editorial magazine grid with overlapping cinematic typography.",
    category: "Editorial",
    style: "Light",
    tags: ["Editorial", "Grid", "Magazine"],
  },
  {
    id: "impact-66",
    name: "Recipe Lab",
    description: "Interactive gastronomy protocol with ingredient anatomy.",
    category: "Luxury",
    style: "Light",
    tags: ["Food", "Interactive", "Brutalist"],
  },
  {
    id: "impact-67",
    name: "Plan 067",
    description: "HUD-inspired room switcher for high-end real estate.",
    category: "Minimal",
    style: "Dark",
    tags: ["Real Estate", "HUD", "Architecture"],
  },
  {
    id: "impact-68",
    name: "Orbit OS",
    description: "Rotating typographic path centered around a project reveal.",
    category: "Creative",
    style: "Light",
    tags: ["Creative", "Typography", "Portfolio"],
  },
  {
    id: "impact-69",
    name: "Depth OS",
    description: "Cinematic parallax depth zoom transitions for nature narratives.",
    category: "Minimal",
    style: "Dark",
    tags: ["Slider", "Parallax", "Nature"],
  },
  {
    id: "impact-70",
    name: "Crypto Node",
    description: "High-tech fintech dashboard with live data visualization.",
    category: "Tech",
    style: "Dark",
    tags: ["Dynamic Content", "Fintech", "HUD"],
  },
  {
    id: "impact-71",
    name: "Archive 35mm",
    description: "Simulated analog film grain and sprocket frame story.",
    category: "Luxury",
    style: "Dark",
    tags: ["Photography", "Film", "Nostalgic"],
  },
  {
    id: "impact-72",
    name: "Stack Unit",
    description: "3D fan-out project stack with spring physics.",
    category: "Creative",
    style: "Light",
    tags: ["Carousel", "3D", "Portfolio"],
  },
  {
    id: "impact-73",
    name: "Glitch Unit",
    description: "Aggressive cyber hero with procedural glitch effects.",
    category: "Tech",
    style: "Dark",
    tags: ["Hero", "Glitch", "Cyber"],
  },
  {
    id: "impact-74",
    name: "Aevia Kitchen",
    description: "Fine dining liquid menu with circular clip-path transitions.",
    category: "Luxury",
    style: "Light",
    tags: ["Food", "Slider", "Luxury"],
  },
  {
    id: "impact-75",
    name: "Spin Unit",
    description: "Interactive 3D product rotation for high-end e-commerce.",
    category: "Luxury",
    style: "Light",
    tags: ["E-commerce", "360", "Interactive"],
  },
  {
    id: "impact-76",
    name: "Glass OS",
    description: "Floating UI glass panels over cinematic nature backgrounds.",
    category: "Creative",
    style: "Dark",
    tags: ["Video", "Glassmorphism", "Creative"],
  },
  {
    id: "impact-77",
    name: "Tilt Grid",
    description: "Modular photography grid with 3D tilt interaction.",
    category: "Minimal",
    style: "Light",
    tags: ["Photography", "Grid", "Interactive"],
  },
  {
    id: "impact-78",
    name: "Voxel OS",
    description: "Typography composed of virtual particles with shatter animations.",
    category: "Creative",
    style: "Dark",
    tags: ["Typography", "Special FX", "Creative"],
  },
  {
    id: "impact-79",
    name: "Reveal OS",
    description: "Pinned horizontal section reveals with massive topographic anchors.",
    category: "Minimal",
    style: "Dark",
    tags: ["One-Page", "Horizontal", "Minimal"],
  },
  {
    id: "impact-80",
    name: "Lava OS",
    description: "Visceral liquid cursor trail with simulated surface tension.",
    category: "Creative",
    style: "Dark",
    tags: ["Interactive", "Liquid", "Gooey"],
  },
  {
    id: "impact-81",
    name: "Vogue Noire",
    description: "Premium high-end fashion magazine with asymmetric mosaic grids, cultural entropy data, and modular boutique showcases.",
    category: "Editorial",
    style: "Light",
    tags: ["Fashion", "Magazine", "Mosaic", "Editorial"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-82",
    name: "Blueprint Developments",
    description: "Institutional luxury real estate developer theme with masterplan grids, structural audits, and investor portals.",
    category: "Tech",
    style: "Dark",
    tags: ["Real Estate", "Architecture", "Investor", "Tech"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-83",
    name: "Aurelius Heritage",
    description: "Ultra-luxury fine jewelry and watch maison with interactive gemstone reveals and historical artisan timelines.",
    category: "Luxury",
    style: "Dark",
    tags: ["Jewelry", "Watches", "Artisan", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-84",
    name: "Cypher Clinic",
    description: "Elite aesthetic medicine clinic with interactive treatment audits, specialist dossiers, and medical safety protocols.",
    category: "Luxury",
    style: "Light",
    tags: ["Beauty", "Clinic", "Medical", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-85",
    name: "Aether Labs",
    description: "High-end skincare laboratory with molecular formulation reveal, clinical outcome data, and bespoke skin concierge.",
    category: "Minimal",
    style: "Light",
    tags: ["Skincare", "Laboratory", "Minimal", "Beauty"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-86",
    name: "Aura Wellness",
    description: "Premium luxury spa & wellness sanctuary with interactive ritual menus, amenity carousels, botanical audits, and a serif-minimalist mega footer.",
    category: "Luxury",
    style: "Light",
    tags: ["Wellness", "Spa", "Luxury", "Botanical"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-87",
    name: "CipherShield",
    description: "Enterprise cybersecurity SaaS with live threat dashboard, red-team case studies, certifications grid, and a dark-tech mega footer.",
    category: "Tech",
    style: "Dark",
    tags: ["Cybersecurity", "SaaS", "Dashboard", "Tech"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-88",
    name: "Velvet Nails",
    description: "Premium nail art salon with filterable portfolio, booking modal, treatment menu, artist profiles, and a rose-gold mega footer.",
    category: "Luxury",
    style: "Light",
    tags: ["Beauty", "Nails", "Salon", "Luxury"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-89",
    name: "Ink & Iron",
    description: "Luxury tattoo & piercing studio with dark-brutalist aesthetic, filterable portfolio, sterilization audit, and artist profiles.",
    category: "Luxury",
    style: "Dark",
    tags: ["Tattoo", "Studio", "Brutalist", "Art"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-90",
    name: "Maison Laval",
    description: "High-end artisan French bakery with interactive product menu, philosophy grid, review wall, and a gold-serif luxury footer.",
    category: "Services",
    style: "Light",
    tags: ["Bakery", "Food", "Artisan", "French"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-91",
    name: "Aurelia Jewels",
    description: "High-fidelity jewelry atelier with seasonal archives, bespoke service blueprints, artisanship stats, and gold-serif luxury design.",
    category: "Luxury",
    style: "Light",
    tags: ["Jewelry", "Atelier", "Luxury", "E-commerce"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-92",
    name: "Skyline Concierge",
    description: "Ultra-luxury real estate & concierge group with interactive private listings, ecosystem capability grids, and dark-marble aesthetic.",
    category: "Luxury",
    style: "Dark",
    tags: ["Real Estate", "Concierge", "Investment", "HNWI"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-93",
    name: "Velocity Jets",
    description: "Private jet charter platform with fleet explorers, network telemetry HUDs, global logistics grids, and cyan-neon tech aesthetic.",
    category: "Services",
    style: "Dark",
    tags: ["Aviation", "Travel", "Logistics", "Tech"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-94",
    name: "Botanica Flowers",
    description: "Luxury floral atelier with seasonal arrangement archives, architectural botany grids, and elegant cream-pastel philosophy deep-dives.",
    category: "Luxury",
    style: "Light",
    tags: ["Florist", "Events", "Subscription", "Art"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-95",
    name: "Lumière Clinic",
    description: "Premium aesthetic medicine clinic with treatment protocols, diagnostic deep-dives, scientific foundation grids, and clinical-minimalist design.",
    category: "Health",
    style: "Light",
    tags: ["Medical", "Wellness", "Longevity", "Aesthetics"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-96",
    name: "Urban Pulse",
    description: "High-energy cinematic studio with horizontal project archives, visual engineering service grids, and bold street-lifestyle design.",
    category: "Creative",
    style: "Dark",
    tags: ["Photography", "Studio", "Cinematic", "Lifestyle"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-97",
    name: "Horizon Yacht",
    description: "Ultra-luxury yacht charter platform with interactive fleet manifest archives, naval infrastructure grids, and destination itinerary deep-dives.",
    category: "Luxury",
    style: "Dark",
    tags: ["Yacht", "Travel", "Luxury", "Charter"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-98",
    name: "Zenith Watches",
    description: "Premium Swiss horology atelier with caliber specification archives, craftsmanship service modules, and heritage philosophy deep-dives.",
    category: "Luxury",
    style: "Dark",
    tags: ["Watches", "Swiss", "Jewelry", "Craftsmanship"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-99",
    name: "Ember Grill",
    description: "High-end wood-fired steakhouse with seasonal menu archives, fire lab philosophy grids, and cellar experience deep-dives.",
    category: "Hospitality",
    style: "Dark",
    tags: ["Restaurant", "Dining", "Luxury", "Wine"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-100",
    name: "Nova Spaces",
    description: "Minimalist high-end interior design studio with project archive grids, spatial psychology service modules, and atelier deep-dives.",
    category: "Luxury",
    style: "Light",
    tags: ["Architecture", "Interior", "Design", "Minimalist"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-101",
    name: "BLOCK // BASE",
    description: "Developer Platform SPA with high-tech terminal aesthetics and telemetry manifests.",
    category: "Tech",
    style: "Dark",
    tags: ["Blockchain", "SDK", "Terminal", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-102",
    name: "QUANTUM // COMPUTE",
    description: "Quantum Computing SPA with spectral wave interference and probabilistic manifests.",
    category: "Tech",
    style: "Dark",
    tags: ["Quantum", "Compute", "Scientific", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-103",
    name: "NEURAL // LINK",
    description: "Brain-Machine Interface SPA with synaptic pulse animations and cortical layer manifests.",
    category: "Tech",
    style: "Dark",
    tags: ["Neural", "BMI", "Cyberpunk", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-104",
    name: "ORBIT // STATION",
    description: "Space Logistics SPA with orbital tracking animations and telemetry manifests.",
    category: "Tech",
    style: "Dark",
    tags: ["Space", "Logistics", "Aerospace", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-105",
    name: "GENE // SEQ",
    description: "Genomics Research SPA with helix deformation animations and sequence manifests.",
    category: "Tech",
    style: "Dark",
    tags: ["Genomics", "Science", "DNA", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-106",
    name: "Studio Versa",
    description: "Multidisciplinary creative studio SPA with project list hover effects, capability grid, awards section, and warm orange-on-cream aesthetic.",
    category: "Creative",
    style: "Light",
    tags: ["Studio", "Portfolio", "Branding", "Awards"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-107",
    name: "Meridian Journey",
    description: "Expedition storytelling SPA with sticky parallax chapters, field-journal gear grid, and teal-wilderness aesthetic.",
    category: "Creative",
    style: "Dark",
    tags: ["Expedition", "Storytelling", "Parallax", "Travel"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-108",
    name: "Chronos Engine",
    description: "High-frequency temporal execution SPA with ticker-tape animations, market telemetry HUD, and gold-industrial aesthetic.",
    category: "Tech",
    style: "Dark",
    tags: ["HFT", "Fintech", "Dashboard", "Telemetry"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-109",
    name: "Signal Mesh",
    description: "IoT mesh network infrastructure SPA with node-pulse animations, telemetry HUD, and purple-industrial aesthetic.",
    category: "Tech",
    style: "Dark",
    tags: ["IoT", "Infrastructure", "Mesh", "Telemetry"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-110",
    name: "Pyro Sentinel",
    description: "Wildfire defense SPA with thermal shimmer effects, drone fleet telemetry, and orange-industrial fire monitoring aesthetic.",
    category: "Tech",
    style: "Dark",
    tags: ["Wildfire", "Defense", "Drones", "Telemetry"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-111",
    name: "Orbit Relay",
    description: "Deep-space communication SPA with orbital ring animations, probe fleet telemetry, and cyan-industrial aesthetic.",
    category: "Tech",
    style: "Dark",
    tags: ["Space", "Communications", "Telemetry", "Deep-Space"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-112",
    name: "Artisan Minimal",
    description: "Minimal artisan e-commerce grid with warm tones and hover cart buttons.",
    category: "Minimal",
    style: "Light",
    tags: ["E-commerce", "Minimal", "Artisan"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-113",
    name: "Nexus SaaS",
    description: "Modern SaaS one-page landing with violet accents, dashboard hero, and feature grid.",
    category: "Tech",
    style: "Dark",
    tags: ["SaaS", "Landing", "Tech"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-114",
    name: "Terra Slider",
    description: "Full-screen curtain-reveal slider with nature photography and serif titles.",
    category: "Creative",
    style: "Dark",
    tags: ["Slider", "Curtain Reveal", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-115",
    name: "Verda Parallax",
    description: "Multi-speed parallax wave gallery with emerald tones and varied image depths.",
    category: "Creative",
    style: "Dark",
    tags: ["Gallery", "Parallax", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-116",
    name: "Kyoto Teahouse",
    description: "Serene Japanese teahouse menu with washi paper tones and kanji accents.",
    category: "Luxury",
    style: "Light",
    tags: ["Food", "Japanese", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-117",
    name: "Genesis Pharm",
    description: "AI drug discovery SPA with molecular target visualization, clinical pipeline telemetry, and emerald-biotech aesthetic.",
    category: "Tech",
    style: "Dark",
    tags: ["Pharma", "AI", "Biotech", "Telemetry"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-118",
    name: "Formwerk Studio",
    description: "Architecture studio SPA with blueprint grid overlay, parametric section drawings, and sky-blue industrial aesthetic.",
    category: "Tech",
    style: "Dark",
    tags: ["Architecture", "Studio", "Blueprint", "Telemetry"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-119",
    name: "IronX Fitness",
    description: "Elite fitness SPA with heart rate visualization, leaderboard tracker, combat programs, and red-industrial aesthetic.",
    category: "Creative",
    style: "Dark",
    tags: ["Fitness", "Gym", "Leaderboard", "Combat"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-120",
    name: "Éclat Parfum",
    description: "Luxury perfume house SPA with molecule visualization, expanding scent rings, rare botanicals, and deep plum-purple aesthetic.",
    category: "Luxury",
    style: "Dark",
    tags: ["Perfume", "Luxury", "Fragrance", "Botanical"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-121",
    name: "Folio Studio",
    description: "Creative portfolio SPA with hover-reveal project list, services grid, awards section, and clean monochrome light-theme aesthetic.",
    category: "Creative",
    style: "Light",
    tags: ["Portfolio", "Studio", "Awards", "Monochrome"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-122",
    name: "Chronicle Editorial",
    description: "Editorial magazine SPA with reading progress bar, featured long-read cards, serif typography, and amber-editorial aesthetic.",
    category: "Editorial",
    style: "Light",
    tags: ["Editorial", "Magazine", "Long-Form", "Journalism"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-123",
    name: "Maison Fashion",
    description: "Fashion house SPA with AW26 lookbook, atelier craftsmanship section, press quotes, and gold-couture aesthetic.",
    category: "Luxury",
    style: "Dark",
    tags: ["Fashion", "Couture", "Lookbook", "Atelier"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-124",
    name: "Morph Studio",
    description: "Motion design studio SPA with morphing blob hero, scroll-linked scale, project list hover effects, and fuchsia-creative aesthetic.",
    category: "Creative",
    style: "Dark",
    tags: ["Motion", "Studio", "Real-Time", "Film"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-125",
    name: "Aura Interactive",
    description: "Interactive design lab SPA with custom cursor aura, radar sweep, haptic research grid, and cyan-interactive aesthetic.",
    category: "Tech",
    style: "Dark",
    tags: ["Interactive", "Haptic", "Installation", "Lab"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-126",
    name: "Trattoria Menu",
    description: "Italian restaurant tabbed menu with warm leather tones and orange accents.",
    category: "Luxury",
    style: "Dark",
    tags: ["Food", "Menu", "Italian"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-127",
    name: "Pulse Events",
    description: "Live events SPA with equalizer bars, pulsing status indicators, event list hover effects, and neon pink-concert aesthetic.",
    category: "Creative",
    style: "Dark",
    tags: ["Events", "Music", "Festival", "Neon"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-128",
    name: "Haven Estates",
    description: "Luxury real estate SPA with property card grid, listing specs, investment advisory, and warm gold-on-cream light-theme aesthetic.",
    category: "Luxury",
    style: "Light",
    tags: ["Real Estate", "Luxury", "Listings", "Investment"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-129",
    name: "Wave FX",
    description: "Open-source dev tools SPA with animated sine waves, code snippets, telemetry dashboard, and indigo-developer aesthetic.",
    category: "Tech",
    style: "Dark",
    tags: ["DevTools", "Open-Source", "WebGL", "SDK"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-130",
    name: "Split Reveal",
    description: "Split-screen slider with left image and right content, emerald accents.",
    category: "Creative",
    style: "Dark",
    tags: ["Slider", "Split", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-131",
    name: "Cuvée Prestige",
    description: "Wine showcase hero with deep burgundy tones, vineyard backdrop, and bottle presentation.",
    category: "Luxury",
    style: "Dark",
    tags: ["Wine", "Luxury", "Showcase"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-132",
    name: "Elementum",
    description: "Clean alternating-row portfolio with nature imagery and ultra-light typography.",
    category: "Minimal",
    style: "Light",
    tags: ["Portfolio", "Alternating", "Minimal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-133",
    name: "Atlas Zoom",
    description: "Dramatic zoom-out reveal hero with city skyline and sky-blue accents.",
    category: "Creative",
    style: "Dark",
    tags: ["Hero", "Zoom", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-134",
    name: "Lumière Beauty",
    description: "Beauty/skincare e-commerce grid with peach tones and rose accent tags.",
    category: "Luxury",
    style: "Light",
    tags: ["Beauty", "E-commerce", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-135",
    name: "Trade OS",
    description: "Live stock ticker dashboard with dynamic data updates, green/red indicators.",
    category: "Tech",
    style: "Dark",
    tags: ["Fintech", "Dashboard", "Tech"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-136",
    name: "Text Reveal",
    description: "Text mask scroll reveal where background image expands through scroll-linked inset clip-path.",
    category: "Creative",
    style: "Dark",
    tags: ["Scroll Reveal", "Text Mask", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-137",
    name: "Torréfié Coffee",
    description: "Specialty coffee roaster one-page with warm paper tones and origin card grid.",
    category: "Minimal",
    style: "Light",
    tags: ["Coffee", "One-Page", "Minimal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-138",
    name: "Prism Analytics",
    description: "Glassmorphism analytics dashboard with gradient background, bar chart, and metric cards.",
    category: "Tech",
    style: "Dark",
    tags: ["Analytics", "Dashboard", "Tech"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-139",
    name: "Apex Automotive",
    description: "Luxury automotive SPA with model selector tabs, performance telemetry bars, RPM gauge animation, and red-industrial motorsport aesthetic.",
    category: "Luxury",
    style: "Dark",
    tags: ["Automotive", "Luxury", "Performance", "Configurator"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-140",
    name: "Wanderlust",
    description: "Travel agency hero with destination cards, amber accents, and full-bleed landscape.",
    category: "Minimal",
    style: "Dark",
    tags: ["Travel", "Hero", "Minimal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-141",
    name: "Sonic Player",
    description: "Music player hero with album art, progress bar, and purple glow effects.",
    category: "Creative",
    style: "Dark",
    tags: ["Music", "Player", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-142",
    name: "Verdant Impact",
    description: "Sustainability landing page with features grid, impact metrics, testimonials, pricing table, contact form, and green-earth light aesthetic.",
    category: "Minimal",
    style: "Light",
    tags: ["Sustainability", "Landing", "Pricing", "Contact"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-143",
    name: "Atelier Interior",
    description: "Interior design site vitrine with about section, services grid, portfolio showcase, testimonials, and warm taupe-luxury light aesthetic.",
    category: "Luxury",
    style: "Light",
    tags: ["Interior", "Vitrine", "Portfolio", "Services"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-144",
    name: "Kinetic Marquee",
    description: "Kinetic typography landing page with dual marquee bands, features grid, testimonials, pricing table, and orange-creative dark aesthetic.",
    category: "Creative",
    style: "Dark",
    tags: ["Typography", "Landing", "Pricing", "Testimonials"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-145",
    name: "Deepcast",
    description: "Podcast landing with episode list, play buttons, and yellow accent on deep navy.",
    category: "Creative",
    style: "Dark",
    tags: ["Podcast", "Landing", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-146",
    name: "Velos FinTech",
    description: "Crypto wallet landing page with portfolio dashboard mockup, features grid, testimonials, pricing plans, and cyan-fintech dark aesthetic.",
    category: "Tech",
    style: "Dark",
    tags: ["FinTech", "Crypto", "Landing", "Pricing"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-147",
    name: "Void Arch",
    description: "Minimalist Black & White architecture portfolio with staggered layout and grayscale-to-color reveals.",
    category: "Minimal",
    style: "Light",
    tags: ["Architecture", "Portfolio", "B&W"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-148",
    name: "Pureté Skincare",
    description: "Organic skincare storytelling with soft cream tones, delicate serif typography, and botanical atmosphere.",
    category: "Luxury",
    style: "Light",
    tags: ["Skincare", "Storytelling", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-149",
    name: "Nørdic Furniture",
    description: "High-end furniture showcase with 3D perspective transitions and bold italic typography.",
    category: "Luxury",
    style: "Dark",
    tags: ["Furniture", "3D", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-150",
    name: "Neon Unit Apparel",
    description: "Cyberpunk-themed apparel shop with neon cyan accents, glitch aesthetic, and technical data overlays.",
    category: "Tech",
    style: "Dark",
    tags: ["Cyberpunk", "Apparel", "E-commerce"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-151",
    name: "Chronos Lab",
    description: "Luxury watch technical detail page with scroll-linked zoom, HUD-inspired overlays, and bold italic typography.",
    category: "Luxury",
    style: "Dark",
    tags: ["Watch", "Technical", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-152",
    name: "Wanderer Mag",
    description: "Travel magazine site vitrine with about, destinations grid, services, testimonials, pricing plans, newsletter, and warm amber-cream aesthetic.",
    category: "Editorial",
    style: "Light",
    tags: ["Travel", "Vitrine", "Pricing", "Testimonials"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-153",
    name: "Véloce Team",
    description: "Engineering agency landing page with features grid, stats counters, testimonials, pricing tiers, and purple-tech dark aesthetic.",
    category: "Tech",
    style: "Dark",
    tags: ["Agency", "Landing", "Pricing", "Tech"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-154",
    name: "Obliq Services",
    description: "Creative agency site vitrine with about, services grid, portfolio, testimonials, pricing, and rose-crimson dark aesthetic.",
    category: "Creative",
    style: "Dark",
    tags: ["Agency", "Vitrine", "Portfolio", "Pricing"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-155",
    name: "Art Index",
    description: "Digital art gallery landing with collections, features grid, testimonials, membership pricing, and purple-creative dark aesthetic.",
    category: "Creative",
    style: "Dark",
    tags: ["Art", "Gallery", "Landing", "Pricing"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-156",
    name: "Bio Form Arch",
    description: "Sustainable architecture site vitrine with about, project portfolio, services grid, testimonials, and sage-green light aesthetic.",
    category: "Minimal",
    style: "Light",
    tags: ["Architecture", "Vitrine", "Services", "Sustainability"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-157",
    name: "Aurum Jewelry",
    description: "Ultra-premium jewelry e-commerce detail page with deep obsidian tones, gold accents, and a focus on high-end sculptural photography.",
    category: "Luxury",
    style: "Dark",
    tags: ["Jewelry", "E-commerce", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-158",
    name: "Proto Log",
    description: "Aggressive neo-brutalist editorial layout with thick black borders, stark monochromatic typography, and high-impact hover effects.",
    category: "Editorial",
    style: "Light",
    tags: ["Brutalist", "Editorial", "News"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-159",
    name: "Re Con Tech",
    description: "High-energy tech event landing with dynamic countdown, neon gradient accents, and immersive particle-style background effects.",
    category: "Tech",
    style: "Dark",
    tags: ["Event", "Tech", "Countdown"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-160",
    name: "Maison V Lookbook",
    description: "Minimalist staggered fashion lookbook with high-contrast monochrome design, hover effects, and bold heroic headings.",
    category: "Minimal",
    style: "Light",
    tags: ["Fashion", "Lookbook", "Minimal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-161",
    name: "Essential SaaS",
    description: "Clean SaaS Landing Page with WordPress/Elementor-ready semantic HTML block structure.",
    category: "Free",
    style: "Light",
    tags: ["SaaS", "Landing", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-162",
    name: "Essential Cafe",
    description: "Local Cafe theme with warm colors, classic layout, and direct WordPress container mapping.",
    category: "Free",
    style: "Light",
    tags: ["Local Business", "Food", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-163",
    name: "Essential Blog",
    description: "Clean Personal Blog layout with sidebar, classic typography, and WordPress-ready structure.",
    category: "Free",
    style: "Light",
    tags: ["Blog", "Personal", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-164",
    name: "Essential Agency",
    description: "Minimalist B&W Agency layout, strictly structured for easy WordPress conversion.",
    category: "Free",
    style: "Dark",
    tags: ["Agency", "Portfolio", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-165",
    name: "Essential App",
    description: "App Promo landing page with simple device mockup and bright, clean UI structure.",
    category: "Free",
    style: "Light",
    tags: ["App", "Promo", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-166",
    name: "Essential Photography",
    description: "Clean dark-mode Photography Portfolio using CSS columns for an easy Masonry grid.",
    category: "Free",
    style: "Dark",
    tags: ["Photography", "Portfolio", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-167",
    name: "Essential Real Estate",
    description: "Clean Real Estate listing block with search hero element, standard flex/grid usage.",
    category: "Free",
    style: "Light",
    tags: ["Real Estate", "Listing", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-168",
    name: "Essential E-Commerce",
    description: "Minimalist E-Commerce layout with hero banner and standard product grid.",
    category: "Free",
    style: "Light",
    tags: ["E-commerce", "Shop", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-169",
    name: "Essential Newsletter",
    description: "Newsletter signup landing page, highly conversion-focused with elegant typography.",
    category: "Free",
    style: "Light",
    tags: ["Newsletter", "Landing", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-170",
    name: "Essential CV",
    description: "Consultant CV/Resume layout with solid structural hierarchy and clean sidebar.",
    category: "Free",
    style: "Light",
    tags: ["CV", "Resume", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-171",
    name: "Essential Medical",
    description: "Medical/Clinic layout with trust-building elements, emergency banner, and service grids.",
    category: "Free",
    style: "Light",
    tags: ["Medical", "Health", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-172",
    name: "Essential Law Firm",
    description: "Law Firm structure with serif typography, elegant sections, and trust-focused layout.",
    category: "Free",
    style: "Light",
    tags: ["Law", "Corporate", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-173",
    name: "Essential Construction",
    description: "Construction/Contractor layout with bold, industrial aesthetic and yellow accents.",
    category: "Free",
    style: "Dark",
    tags: ["Construction", "Industrial", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-174",
    name: "Essential Fitness",
    description: "High-energy Fitness/Gym layout with dark styling, cyan highlights, and bold typography.",
    category: "Free",
    style: "Dark",
    tags: ["Fitness", "Gym", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-175",
    name: "Essential Event",
    description: "Event/Conference landing page with vibrant colors, simple speaker grid, and clear CTA.",
    category: "Free",
    style: "Vibrant",
    tags: ["Event", "Conference", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-176",
    name: "Essential Dashboard",
    description: "Clean SaaS Admin dashboard structure using native CSS grids and simple UI components.",
    category: "Free",
    style: "Light",
    tags: ["Dashboard", "SaaS", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-177",
    name: "Essential Podcast",
    description: "Tech Podcast landing page with elegant dark mode, audio player hints, and list block.",
    category: "Free",
    style: "Dark",
    tags: ["Podcast", "Media", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-178",
    name: "Essential Cleaning",
    description: "Light and Trustworthy Cleaning Service landing page with review badges and ZIP code form.",
    category: "Free",
    style: "Light",
    tags: ["Service", "Local Business", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-179",
    name: "Essential Non-profit",
    description: "Non-profit charity landing page with emotional photography, serif headers, and donation CTA.",
    category: "Free",
    style: "Light",
    tags: ["Charity", "Non-profit", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-180",
    name: "Essential Salon",
    description: "Premium Barber/Salon split-screen layout with dark aesthetic and price list.",
    category: "Free",
    style: "Dark",
    tags: ["Salon", "Barber", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-181",
    name: "Nexus Web3",
    description: "Premium Web3/Crypto landing page with floating ORB backgrounds, glassmorphism UI, and fluid animations.",
    category: "Tech",
    style: "Vibrant",
    tags: ["Web3", "Crypto", "DeFi"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-182",
    name: "The Grand Hotel",
    description: "Premium Luxury Hotel landing page with elegant serif fonts, parallax feels, and large immersive photography.",
    category: "Luxury",
    style: "Light",
    tags: ["Hotel", "Travel", "Elegant"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-183",
    name: "Cognix AI",
    description: "Premium AI SaaS Platform featuring neumorphic glass impacts, dark mode glows, and generative interface hints.",
    category: "Tech",
    style: "Dark",
    tags: ["AI", "SaaS", "Dashboard"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-184",
    name: "MoMA Structure",
    description: "Premium Modern Museum with Brutalist sidebar layout, extreme typography and solid borders.",
    category: "Creative",
    style: "Light",
    tags: ["Museum", "Art", "Brutalist"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-185",
    name: "Velma Editorial",
    description: "Premium Fashion Brand layout featuring massive hero text blending with background photography.",
    category: "Editorial",
    style: "Light",
    tags: ["Fashion", "Lookbook", "Oversized Text"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-186",
    name: "ArchiTectura",
    description: "Premium Architecture firm structural grid with brutalist grayscale hover reveals.",
    category: "Minimal",
    style: "Dark",
    tags: ["Architecture", "Studio", "Grayscale"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-187",
    name: "Vault FinTech",
    description: "Premium FinTech Interface with glowing charts, deep blue/emerald gradients, and glassmorphism.",
    category: "Tech",
    style: "Dark",
    tags: ["FinTech", "App", "Gradients"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-188",
    name: "Cinema Roster",
    description: "Premium Film Production horizontal-scroll aesthetic with cinematic typography and giant cinematic tiles.",
    category: "Creative",
    style: "Dark",
    tags: ["Film", "Production", "Horizontal Scroll"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-189",
    name: "Aura Dining",
    description: "Premium Restaurant/Dining layout with dark romantic themes, elegant thin serifs, and tall image masks.",
    category: "Luxury",
    style: "Dark",
    tags: ["Restaurant", "Dining", "Romantic"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-190",
    name: "Nexus Gaming",
    description: "Premium Cyberpunk/Gaming Studio landing page with neon grid effects, glitch-inspired text, and stark lines.",
    category: "Tech",
    style: "Dark",
    tags: ["Gaming", "Cyberpunk", "Neon"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-191",
    name: "Premium Interior",
    description: "Elegant interior design showcase with minimalist layouts and smooth scroll transitions.",
    category: "Luxury",
    style: "Light",
    tags: ["Interior", "Architecture", "Minimal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-192",
    name: "Premium Fragrance",
    description: "High-end perfume landing page with cinematic parallax and deep ambient aesthetics.",
    category: "Luxury",
    style: "Dark",
    tags: ["Fragrance", "Luxury", "Parallax"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-193",
    name: "Premium Festival",
    description: "Dynamic event experience with vibrant colors, kinetic typography, and fluid schedules.",
    category: "Creative",
    style: "Vibrant",
    tags: ["Event", "Festival", "Vibrant"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-194",
    name: "Premium Web Agency",
    description: "Modern creative studio showcase with bold grid layouts and technical details.",
    category: "Creative",
    style: "Dark",
    tags: ["Agency", "Portfolio", "Grid"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-195",
    name: "Premium Bakery",
    description: "Artisanal food experience with elegant serif typography and warm atmospheric lighting.",
    category: "Luxury",
    style: "Light",
    tags: ["Food", "Bakery", "Artisanal"],
    tier: "Premium",
    sections: 15,
  },
];
