export interface TemplateMetadata {
  id: string;
  name: string;
  description: string;
  category: "Tech" | "Luxury" | "Editorial" | "Creative" | "Minimal" | "Free" | "Corporate" | "E-Commerce" | "Health" | "Hospitality" | "Services" | "Education";
  style: "Dark" | "Light" | "Vibrant";
  tags: string[];
  tier: "Essentiel" | "Pro" | "Premium";
  sections: number;
}

export const TEMPLATES_REGISTRY: TemplateMetadata[] = [
  {
    id: "impact-01",
    name: "NOVA Agency",
    description: "Full multi-section agency vitrine with scroll animations, magnetic buttons, portfolio carousel, and contact form.",
    category: "Creative",
    style: "Dark",
    tags: ["Agency", "Vitrine", "Multi-Section", "Animated"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-02",
    name: "Elena Korr Portfolio",
    description: "Cinematic photographer portfolio with filterable masonry gallery, fullscreen project modals, and awards section.",
    category: "Creative",
    style: "Dark",
    tags: ["Portfolio", "Photography", "Masonry", "Modal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-03",
    name: "Maison Dorée",
    description: "Luxury e-commerce boutique with 3D tilt product cards, cart drawer, wishlist, lookbook gallery, and product detail views.",
    category: "Luxury",
    style: "Light",
    tags: ["E-commerce", "Luxury", "3D Tilt", "Cart"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-04",
    name: "L'Étoile Restaurant",
    description: "Fine dining restaurant vitrine with tabbed animated menu, reservation modal, ambiance gallery, and chef story section.",
    category: "Luxury",
    style: "Dark",
    tags: ["Restaurant", "Vitrine", "Menu", "Reservation"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-05",
    name: "NovaPlatform SaaS",
    description: "Modern SaaS landing with floating UI cards, feature grid, timeline, pricing toggle, testimonials, and conversion CTAs.",
    category: "Tech",
    style: "Dark",
    tags: ["SaaS", "Pricing", "Timeline", "Marketplace"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-06",
    name: "Neuralis",
    description: "Premium neuro-tech interface with real-time neural bridge diagnostics, biological integrity audits, and clinical trial data visualization.",
    category: "Tech",
    style: "Dark",
    tags: ["Neuro-Tech", "HUD", "Clinical", "Interactive"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-07",
    name: "Aether Sound",
    description: "Ultra-luxury high-fidelity audio boutique with acoustic engineering manifests, artisan luthier profiles, and heritage timelines.",
    category: "Luxury",
    style: "Dark",
    tags: ["Audio", "Hi-Fi", "Artisan", "Heritage"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-08",
    name: "Vulcan Motors",
    description: "Elite automotive atelier featuring hypercar performance manifests, aerodynamic logic audits, and bespoke 1-of-1 customization portals.",
    category: "Luxury",
    style: "Dark",
    tags: ["Automotive", "Hypercar", "Performance", "Bespoke"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-09",
    name: "Astrum Reach",
    description: "Premium orbital logistics & space tourism manifest with aerospace engineering schematics, mission command dossiers, and safety protocols.",
    category: "Tech",
    style: "Dark",
    tags: ["Aerospace", "Space", "Logistics", "Safety"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-10",
    name: "Grand Palais",
    description: "Luxury 5-star hotel with dark navy and gold palette, split-screen hero with room cards, parallax scroll, and Cormorant Garamond typography.",
    category: "Hospitality",
    style: "Dark",
    tags: ["Hotel", "Luxury", "Hospitality", "Parallax"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-11",
    name: "EduPath",
    description: "Modern EdTech platform with floating course cards hero, violet gradient pricing, progress tracking, and system-ui typography.",
    category: "Education",
    style: "Light",
    tags: ["EdTech", "Education", "SaaS", "Courses"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-12",
    name: "Noir Couture",
    description: "Editorial fashion brand with B&W split hero, typography stacks, transparent-to-white scroll nav, and editorial grid collections.",
    category: "Fashion",
    style: "Dark",
    tags: ["Fashion", "Editorial", "Luxury", "Minimal"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-13",
    name: "Atelier Mécanique",
    description: "Luxury watchmaking boutique with dark charcoal and brass palette, Cormorant Garamond, and per-card parallax depth effects.",
    category: "Luxury",
    style: "Dark",
    tags: ["Watches", "Horology", "Luxury", "Craftsmanship"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-14",
    name: "Azimut",
    description: "Sailing school with navy and teal palette, animated sine-wave SVG hero, course levels, and instructor profiles.",
    category: "Sports",
    style: "Light",
    tags: ["Sailing", "School", "Sports", "Ocean"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-15",
    name: "Fortress",
    description: "Cybersecurity firm with dark terminal aesthetic, neon green accents, JetBrains Mono, and live cycling security log widget.",
    category: "Tech",
    style: "Dark",
    tags: ["Cybersecurity", "SaaS", "Terminal", "B2B"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-16",
    name: "Obscura",
    description: "Photography studio with dark background, gold accents, grain overlay texture, and rotated photo cards that straighten on hover.",
    category: "Photography",
    style: "Dark",
    tags: ["Photography", "Studio", "Portfolio", "Creative"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-17",
    name: "Kéops",
    description: "Architecture firm with white and terracotta palette, blueprint SVG grid background, and project list with hover terracotta border.",
    category: "Architecture",
    style: "Light",
    tags: ["Architecture", "Studio", "Design", "Portfolio"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-18",
    name: "Streamline",
    description: "SaaS platform with dark navy and electric blue palette, Kanban board hero mockup, and animated feature showcase.",
    category: "SaaS",
    style: "Dark",
    tags: ["SaaS", "Productivity", "B2B", "Dashboard"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-19",
    name: "Summit Capital",
    description: "Venture capital firm with dark and gold palette, Cormorant Garamond, minimalist VC aesthetic, and portfolio company list.",
    category: "Finance",
    style: "Dark",
    tags: ["VC", "Finance", "Investment", "Corporate"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-20",
    name: "Orens Jewelry",
    description: "Fine jewelry house with dark and warm gold palette, scrolling marquee hero, collection cards with hover gold border animation.",
    category: "Luxury",
    style: "Dark",
    tags: ["Jewelry", "Luxury", "E-commerce", "Fashion"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-21",
    name: "Forme Studio",
    description: "Product design studio with white and orange palette, diagonal orange panel hero, sliding tab indicator, and case studies.",
    category: "Design",
    style: "Light",
    tags: ["Product Design", "Studio", "Creative", "Portfolio"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-22",
    name: "NimbusAI",
    description: "Cloud AI platform with dark navy and cyan, animated AI pipeline diagram with pulse dots, and feature comparison table.",
    category: "Tech",
    style: "Dark",
    tags: ["AI", "Cloud", "SaaS", "B2B"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-23",
    name: "Studio Pelikan",
    description: "Film production studio with dark and amber palette, Cormorant Garamond, horizontal film strip with scroll drift parallax.",
    category: "Creative",
    style: "Dark",
    tags: ["Film", "Production", "Cinema", "Studio"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-24",
    name: "Zero to One",
    description: "Startup accelerator with dark and neon lime palette, cohort timeline, inverted lime stats section, and application form.",
    category: "Startup",
    style: "Dark",
    tags: ["Accelerator", "Startup", "VC", "Growth"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-25",
    name: "Prism Analytics",
    description: "Analytics SaaS with dark navy and violet palette, mock bar chart dashboard hero, and animated gradient border cards.",
    category: "SaaS",
    style: "Dark",
    tags: ["Analytics", "SaaS", "Dashboard", "B2B"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-26",
    name: "Éther",
    description: "Luxury fragrance maison with deep plum and rose gold palette, rotating SVG circle hero, and scroll-triggered scale animation.",
    category: "Luxury",
    style: "Dark",
    tags: ["Fragrance", "Luxury", "E-commerce", "Beauty"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-27",
    name: "Vertex Studio",
    description: "3D and AR studio with dark purple palette, perspective-transformed wireframe viewport hero, and immersive project showcases.",
    category: "Creative",
    style: "Dark",
    tags: ["3D", "AR", "Creative Tech", "Studio"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-28",
    name: "Brutco",
    description: "Pure brutalist architecture firm — black and white only, Helvetica 900 ALL CAPS, zero border radius, 4px black borders throughout.",
    category: "Architecture",
    style: "Brutalist",
    tags: ["Architecture", "Brutalist", "Minimal", "B&W"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-29",
    name: "Glitch.dev",
    description: "Developer portfolio with terminal dark aesthetic, neon cyan, JetBrains Mono exclusively, and typed-out hero with // prefix headings.",
    category: "Portfolio",
    style: "Dark",
    tags: ["Developer", "Portfolio", "Terminal", "Tech"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-30",
    name: "Smile Studio",
    description: "Modern dental clinic with white and mint palette, animated tooth SVG hero, treatment cards, team profiles, and trust-first layout.",
    category: "Healthcare",
    style: "Light",
    tags: ["Dental", "Healthcare", "Medical", "Clinic"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-31",
    name: "Ananda Flow",
    description: "Yoga and meditation studio with warm earth tones, Lora/Raleway fonts, animated breathing circle hero, and class schedule grid.",
    category: "Wellness",
    style: "Light",
    tags: ["Yoga", "Wellness", "Studio", "Meditation"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-32",
    name: "PawCare Clinic",
    description: "Friendly veterinary clinic with forest green palette, animated paw print hero, pet species tabs, and 3-plan pricing.",
    category: "Healthcare",
    style: "Light",
    tags: ["Veterinary", "Pet Care", "Clinic", "Animals"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-33",
    name: "La Fournée",
    description: "Artisan bakery with warm ivory and brown palette, Playfair Display headings, scrolling pastry marquee, and menu by category.",
    category: "Food & Drink",
    style: "Light",
    tags: ["Bakery", "Food", "Artisan", "Café"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-34",
    name: "WaveForm",
    description: "Podcast hosting platform with OLED dark aesthetic, electric purple, animated EQ bars hero, and creator-focused pricing.",
    category: "Tech",
    style: "Dark",
    tags: ["Podcast", "Platform", "Creator", "SaaS"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-35",
    name: "Nexus Hub",
    description: "Premium coworking space with amber palette, Space Grotesk, interactive floor plan, and day/month/year membership tiers.",
    category: "Business",
    style: "Light",
    tags: ["Coworking", "Office", "Community", "Workspace"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-36",
    name: "Apex Talent",
    description: "Executive recruiting firm with deep navy and electric blue, Plus Jakarta Sans, animated placement counters, and industry sectors grid.",
    category: "Corporate",
    style: "Light",
    tags: ["Recruiting", "HR", "Executive", "B2B"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-37",
    name: "Clos du Soir",
    description: "Luxury wine bar with deep burgundy and gold palette, Cormorant Garamond, scroll-driven wine bottle fill animation, and sommelier events.",
    category: "Food & Drink",
    style: "Dark",
    tags: ["Wine", "Bar", "Luxury", "Sommelier"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-38",
    name: "Origin Roast",
    description: "Specialty coffee roastery with espresso and caramel palette, Fraunces headings, world origin map SVG, and subscription box pricing.",
    category: "Food & Drink",
    style: "Dark",
    tags: ["Coffee", "Roastery", "Subscription", "Artisan"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-39",
    name: "Swift Move",
    description: "Moving and logistics company with orange and navy palette, animated truck SVG hero, 4-step process timeline, and instant quote CTA.",
    category: "Services",
    style: "Light",
    tags: ["Moving", "Logistics", "Services", "Local"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-40",
    name: "Terre Vivante",
    description: "Organic farm and CSA subscription with forest green and golden yellow, animated growing plant SVG, seasonal tabs, and farm story.",
    category: "Food & Drink",
    style: "Light",
    tags: ["Farm", "Organic", "CSA", "Local Food"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-41",
    name: "Lumière d'Espoir",
    description: "Humanitarian nonprofit with compassion blue and sunny yellow palette, animated impact counters, donation tiers, and mission programs.",
    category: "Nonprofit",
    style: "Light",
    tags: ["Nonprofit", "NGO", "Humanitarian", "Charity"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-42",
    name: "Echo Chamber",
    description: "Professional recording studio with pure black and neon red palette, Bebas Neue headings, animated EQ bars, and notable artists marquee.",
    category: "Creative",
    style: "Dark",
    tags: ["Music", "Studio", "Recording", "Audio"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-43",
    name: "Serene Retreat",
    description: "Luxury hotel spa with sage and forest green palette, Cormorant Garamond, ripple water animation, thermal circuit steps, and retreat packages.",
    category: "Hospitality",
    style: "Light",
    tags: ["Spa", "Wellness", "Luxury", "Hotel"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-44",
    name: "Espace Studio",
    description: "Interior design studio with warm white and terracotta, DM Serif Display, editorial split hero, filterable project portfolio, and process steps.",
    category: "Design",
    style: "Light",
    tags: ["Interior Design", "Architecture", "Studio", "Portfolio"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-45",
    name: "Noir Ink",
    description: "Premium tattoo studio with near-black and blood red, Cinzel headings, masonry portfolio grid with hover overlays, and booking tiers.",
    category: "Creative",
    style: "Dark",
    tags: ["Tattoo", "Studio", "Art", "Portfolio"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-46",
    name: "Dumont & Associates",
    description: "Boutique law firm with deep navy and gold, Playfair Display, animated justice scale SVG, 6 practice areas, and attorney profiles.",
    category: "Corporate",
    style: "Dark",
    tags: ["Law", "Legal", "Corporate", "B2B"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-47",
    name: "Pétales & Co",
    description: "Artisan florist with blush pink and rose palette, Libre Baskerville, falling petal animation hero, seasonal collections, and bouquet subscription.",
    category: "Retail",
    style: "Light",
    tags: ["Florist", "Flowers", "E-commerce", "Seasonal"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-48",
    name: "Meridian Capital",
    description: "Wealth management firm with dark charcoal and warm gold, Cormorant Garamond, animated portfolio chart SVG, and advisor profiles.",
    category: "Finance",
    style: "Dark",
    tags: ["Finance", "Wealth", "Investment", "Advisory"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-49",
    name: "Skillbridge",
    description: "Online course marketplace with deep purple and teal gradient, Plus Jakarta Sans, search hero, skill progress bars, and 3-plan pricing.",
    category: "Education",
    style: "Dark",
    tags: ["E-learning", "Courses", "Platform", "Education"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-50",
    name: "LIQUID // METAL",
    description: "Viscous fluid interface with liquid manifests and fluid interface shells.",
    category: "Tech",
    style: "Dark",
    tags: ["Fluid", "Metal", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-51",
    name: "LAYER // FX",
    description: "Multi-layered composition interface with layer manifests and system interface shells.",
    category: "Tech",
    style: "Dark",
    tags: ["Layer", "FX", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-52",
    name: "PARTICLE // FIELD",
    description: "Dynamic particle field interface with particle manifests and field interface shells.",
    category: "Tech",
    style: "Dark",
    tags: ["Particle", "Field", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-53",
    name: "MESH // WARP",
    description: "SVG mesh deformation interface with mesh manifests and warp interface shells.",
    category: "Tech",
    style: "Dark",
    tags: ["Mesh", "Warp", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-54",
    name: "ECHO // SCROLL",
    description: "Kinetic typography interface with echo manifests and scroll interface shells.",
    category: "Tech",
    style: "Dark",
    tags: ["Echo", "Scroll", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-55",
    name: "NEON // HUD",
    description: "Sci-Fi HUD interface with neon manifests and HUD interface shells.",
    category: "Tech",
    style: "Dark",
    tags: ["Neon", "HUD", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-56",
    name: "Split Slider",
    description: "Cinematic vertical split transitions for high-end narratives.",
    category: "Editorial",
    style: "Dark",
    tags: ["Slider", "Split", "Editorial"],
  },
  {
    id: "impact-57",
    name: "Mask Unit",
    description: "Large-scale typography with masked background video effects.",
    category: "Creative",
    style: "Light",
    tags: ["Hero", "Masking", "Creative"],
  },
  {
    id: "impact-58",
    name: "Skew OS",
    description: "Kinetic scroll carousel with dynamic skew distortion.",
    category: "Creative",
    style: "Dark",
    tags: ["Carousel", "Kinetic", "Perspective"],
  },
  {
    id: "impact-59",
    name: "Spec 059",
    description: "Technical e-commerce showcase with interactive spec highlighting.",
    category: "Tech",
    style: "Dark",
    tags: ["E-commerce", "Interactive", "HUD"],
  },
  {
    id: "impact-60",
    name: "Stack OS",
    description: "Brutalist photography stack with sticky reveal transitions.",
    category: "Minimal",
    style: "Light",
    tags: ["Photography", "Brutalist", "Gallery"],
  },
  {
    id: "impact-61",
    name: "Segment OS",
    description: "One-page vertical dot navigation with smooth snap segments.",
    category: "Minimal",
    style: "Light",
    tags: ["One-Page", "Navigation", "Minimal"],
  },
  {
    id: "impact-62",
    name: "Liquid OS",
    description: "Visceral 'Gooey' SVG filter transitions for bold typography.",
    category: "Creative",
    style: "Dark",
    tags: ["Typography", "Special FX", "Liquid"],
  },
  {
    id: "impact-63",
    name: "Orbit Unit",
    description: "Scroll-linked luxury product rotation and scaling.",
    category: "Luxury",
    style: "Light",
    tags: ["Luxury", "Parallax", "Product"],
  },
  {
    id: "impact-64",
    name: "Data Stream OS",
    description: "Modern Matrix-inspired data rain with technical code fragments.",
    category: "Tech",
    style: "Dark",
    tags: ["Tech", "Particle Effects", "Matrix"],
  },
  {
    id: "impact-65",
    name: "Complex OS",
    description: "Complex editorial magazine grid with overlapping cinematic typography.",
    category: "Editorial",
    style: "Light",
    tags: ["Editorial", "Grid", "Magazine"],
  },
  {
    id: "impact-66",
    name: "Recipe Lab",
    description: "Interactive gastronomy protocol with ingredient anatomy.",
    category: "Luxury",
    style: "Light",
    tags: ["Food", "Interactive", "Brutalist"],
  },
  {
    id: "impact-67",
    name: "Plan 067",
    description: "HUD-inspired room switcher for high-end real estate.",
    category: "Minimal",
    style: "Dark",
    tags: ["Real Estate", "HUD", "Architecture"],
  },
  {
    id: "impact-68",
    name: "Orbit OS",
    description: "Rotating typographic path centered around a project reveal.",
    category: "Creative",
    style: "Light",
    tags: ["Creative", "Typography", "Portfolio"],
  },
  {
    id: "impact-69",
    name: "Depth OS",
    description: "Cinematic parallax depth zoom transitions for nature narratives.",
    category: "Minimal",
    style: "Dark",
    tags: ["Slider", "Parallax", "Nature"],
  },
  {
    id: "impact-70",
    name: "Crypto Node",
    description: "High-tech fintech dashboard with live data visualization.",
    category: "Tech",
    style: "Dark",
    tags: ["Dynamic Content", "Fintech", "HUD"],
  },
  {
    id: "impact-71",
    name: "Archive 35mm",
    description: "Simulated analog film grain and sprocket frame story.",
    category: "Luxury",
    style: "Dark",
    tags: ["Photography", "Film", "Nostalgic"],
  },
  {
    id: "impact-72",
    name: "Stack Unit",
    description: "3D fan-out project stack with spring physics.",
    category: "Creative",
    style: "Light",
    tags: ["Carousel", "3D", "Portfolio"],
  },
  {
    id: "impact-73",
    name: "Glitch Unit",
    description: "Aggressive cyber hero with procedural glitch effects.",
    category: "Tech",
    style: "Dark",
    tags: ["Hero", "Glitch", "Cyber"],
  },
  {
    id: "impact-74",
    name: "Aevia Kitchen",
    description: "Fine dining liquid menu with circular clip-path transitions.",
    category: "Luxury",
    style: "Light",
    tags: ["Food", "Slider", "Luxury"],
  },
  {
    id: "impact-75",
    name: "Spin Unit",
    description: "Interactive 3D product rotation for high-end e-commerce.",
    category: "Luxury",
    style: "Light",
    tags: ["E-commerce", "360", "Interactive"],
  },
  {
    id: "impact-76",
    name: "Glass OS",
    description: "Floating UI glass panels over cinematic nature backgrounds.",
    category: "Creative",
    style: "Dark",
    tags: ["Video", "Glassmorphism", "Creative"],
  },
  {
    id: "impact-77",
    name: "Tilt Grid",
    description: "Modular photography grid with 3D tilt interaction.",
    category: "Minimal",
    style: "Light",
    tags: ["Photography", "Grid", "Interactive"],
  },
  {
    id: "impact-78",
    name: "Voxel OS",
    description: "Typography composed of virtual particles with shatter animations.",
    category: "Creative",
    style: "Dark",
    tags: ["Typography", "Special FX", "Creative"],
  },
  {
    id: "impact-79",
    name: "Reveal OS",
    description: "Pinned horizontal section reveals with massive topographic anchors.",
    category: "Minimal",
    style: "Dark",
    tags: ["One-Page", "Horizontal", "Minimal"],
  },
  {
    id: "impact-80",
    name: "Lava OS",
    description: "Visceral liquid cursor trail with simulated surface tension.",
    category: "Creative",
    style: "Dark",
    tags: ["Interactive", "Liquid", "Gooey"],
  },
  {
    id: "impact-81",
    name: "Vogue Noire",
    description: "Premium high-end fashion magazine with asymmetric mosaic grids, cultural entropy data, and modular boutique showcases.",
    category: "Editorial",
    style: "Light",
    tags: ["Fashion", "Magazine", "Mosaic", "Editorial"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-82",
    name: "Blueprint Developments",
    description: "Institutional luxury real estate developer theme with masterplan grids, structural audits, and investor portals.",
    category: "Tech",
    style: "Dark",
    tags: ["Real Estate", "Architecture", "Investor", "Tech"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-83",
    name: "Aurelius Heritage",
    description: "Ultra-luxury fine jewelry and watch maison with interactive gemstone reveals and historical artisan timelines.",
    category: "Luxury",
    style: "Dark",
    tags: ["Jewelry", "Watches", "Artisan", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-84",
    name: "Cypher Clinic",
    description: "Elite aesthetic medicine clinic with interactive treatment audits, specialist dossiers, and medical safety protocols.",
    category: "Luxury",
    style: "Light",
    tags: ["Beauty", "Clinic", "Medical", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-85",
    name: "Aether Labs",
    description: "High-end skincare laboratory with molecular formulation reveal, clinical outcome data, and bespoke skin concierge.",
    category: "Minimal",
    style: "Light",
    tags: ["Skincare", "Laboratory", "Minimal", "Beauty"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-86",
    name: "Aura Wellness",
    description: "Premium luxury spa & wellness sanctuary with interactive ritual menus, amenity carousels, botanical audits, and a serif-minimalist mega footer.",
    category: "Luxury",
    style: "Light",
    tags: ["Wellness", "Spa", "Luxury", "Botanical"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-87",
    name: "CipherShield",
    description: "Enterprise cybersecurity SaaS with live threat dashboard, red-team case studies, certifications grid, and a dark-tech mega footer.",
    category: "Tech",
    style: "Dark",
    tags: ["Cybersecurity", "SaaS", "Dashboard", "Tech"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-88",
    name: "Velvet Nails",
    description: "Premium nail art salon with filterable portfolio, booking modal, treatment menu, artist profiles, and a rose-gold mega footer.",
    category: "Luxury",
    style: "Light",
    tags: ["Beauty", "Nails", "Salon", "Luxury"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-89",
    name: "Ink & Iron",
    description: "Luxury tattoo & piercing studio with dark-brutalist aesthetic, filterable portfolio, sterilization audit, and artist profiles.",
    category: "Luxury",
    style: "Dark",
    tags: ["Tattoo", "Studio", "Brutalist", "Art"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-90",
    name: "Maison Laval",
    description: "High-end artisan French bakery with interactive product menu, philosophy grid, review wall, and a gold-serif luxury footer.",
    category: "Services",
    style: "Light",
    tags: ["Bakery", "Food", "Artisan", "French"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-91",
    name: "Aurelia Jewels",
    description: "High-fidelity jewelry atelier with seasonal archives, bespoke service blueprints, artisanship stats, and gold-serif luxury design.",
    category: "Luxury",
    style: "Light",
    tags: ["Jewelry", "Atelier", "Luxury", "E-commerce"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-92",
    name: "Skyline Concierge",
    description: "Ultra-luxury real estate & concierge group with interactive private listings, ecosystem capability grids, and dark-marble aesthetic.",
    category: "Luxury",
    style: "Dark",
    tags: ["Real Estate", "Concierge", "Investment", "HNWI"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-93",
    name: "Velocity Jets",
    description: "Private jet charter platform with fleet explorers, network telemetry HUDs, global logistics grids, and cyan-neon tech aesthetic.",
    category: "Services",
    style: "Dark",
    tags: ["Aviation", "Travel", "Logistics", "Tech"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-94",
    name: "Botanica Flowers",
    description: "Luxury floral atelier with seasonal arrangement archives, architectural botany grids, and elegant cream-pastel philosophy deep-dives.",
    category: "Luxury",
    style: "Light",
    tags: ["Florist", "Events", "Subscription", "Art"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-95",
    name: "Lumière Clinic",
    description: "Premium aesthetic medicine clinic with treatment protocols, diagnostic deep-dives, scientific foundation grids, and clinical-minimalist design.",
    category: "Health",
    style: "Light",
    tags: ["Medical", "Wellness", "Longevity", "Aesthetics"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-96",
    name: "Urban Pulse",
    description: "High-energy cinematic studio with horizontal project archives, visual engineering service grids, and bold street-lifestyle design.",
    category: "Creative",
    style: "Dark",
    tags: ["Photography", "Studio", "Cinematic", "Lifestyle"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-97",
    name: "Horizon Yacht",
    description: "Ultra-luxury yacht charter platform with interactive fleet manifest archives, naval infrastructure grids, and destination itinerary deep-dives.",
    category: "Luxury",
    style: "Dark",
    tags: ["Yacht", "Travel", "Luxury", "Charter"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-98",
    name: "Zenith Watches",
    description: "Premium Swiss horology atelier with caliber specification archives, craftsmanship service modules, and heritage philosophy deep-dives.",
    category: "Luxury",
    style: "Dark",
    tags: ["Watches", "Swiss", "Jewelry", "Craftsmanship"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-99",
    name: "Ember Grill",
    description: "High-end wood-fired steakhouse with seasonal menu archives, fire lab philosophy grids, and cellar experience deep-dives.",
    category: "Hospitality",
    style: "Dark",
    tags: ["Restaurant", "Dining", "Luxury", "Wine"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-100",
    name: "Nova Spaces",
    description: "Minimalist high-end interior design studio with project archive grids, spatial psychology service modules, and atelier deep-dives.",
    category: "Luxury",
    style: "Light",
    tags: ["Architecture", "Interior", "Design", "Minimalist"],
    tier: "Premium",
    sections: 12,
  },
  {
    id: "impact-101",
    name: "BLOCK // BASE",
    description: "Developer Platform SPA with high-tech terminal aesthetics and telemetry manifests.",
    category: "Tech",
    style: "Dark",
    tags: ["Blockchain", "SDK", "Terminal", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-102",
    name: "QUANTUM // COMPUTE",
    description: "Quantum Computing SPA with spectral wave interference and probabilistic manifests.",
    category: "Tech",
    style: "Dark",
    tags: ["Quantum", "Compute", "Scientific", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-103",
    name: "NEURAL // LINK",
    description: "Brain-Machine Interface SPA with synaptic pulse animations and cortical layer manifests.",
    category: "Tech",
    style: "Dark",
    tags: ["Neural", "BMI", "Cyberpunk", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-104",
    name: "ORBIT // STATION",
    description: "Space Logistics SPA with orbital tracking animations and telemetry manifests.",
    category: "Tech",
    style: "Dark",
    tags: ["Space", "Logistics", "Aerospace", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-105",
    name: "GENE // SEQ",
    description: "Genomics Research SPA with helix deformation animations and sequence manifests.",
    category: "Tech",
    style: "Dark",
    tags: ["Genomics", "Science", "DNA", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-106",
    name: "Studio Versa",
    description: "Multidisciplinary creative studio SPA with project list hover effects, capability grid, awards section, and warm orange-on-cream aesthetic.",
    category: "Creative",
    style: "Light",
    tags: ["Studio", "Portfolio", "Branding", "Awards"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-107",
    name: "Meridian Journey",
    description: "Expedition storytelling SPA with sticky parallax chapters, field-journal gear grid, and teal-wilderness aesthetic.",
    category: "Creative",
    style: "Dark",
    tags: ["Expedition", "Storytelling", "Parallax", "Travel"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-108",
    name: "Chronos Engine",
    description: "High-frequency temporal execution SPA with ticker-tape animations, market telemetry HUD, and gold-industrial aesthetic.",
    category: "Tech",
    style: "Dark",
    tags: ["HFT", "Fintech", "Dashboard", "Telemetry"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-109",
    name: "Signal Mesh",
    description: "IoT mesh network infrastructure SPA with node-pulse animations, telemetry HUD, and purple-industrial aesthetic.",
    category: "Tech",
    style: "Dark",
    tags: ["IoT", "Infrastructure", "Mesh", "Telemetry"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-110",
    name: "Pyro Sentinel",
    description: "Wildfire defense SPA with thermal shimmer effects, drone fleet telemetry, and orange-industrial fire monitoring aesthetic.",
    category: "Tech",
    style: "Dark",
    tags: ["Wildfire", "Defense", "Drones", "Telemetry"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-111",
    name: "Orbit Relay",
    description: "Deep-space communication SPA with orbital ring animations, probe fleet telemetry, and cyan-industrial aesthetic.",
    category: "Tech",
    style: "Dark",
    tags: ["Space", "Communications", "Telemetry", "Deep-Space"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-112",
    name: "Artisan Minimal",
    description: "Minimal artisan e-commerce grid with warm tones and hover cart buttons.",
    category: "Minimal",
    style: "Light",
    tags: ["E-commerce", "Minimal", "Artisan"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-113",
    name: "Nexus SaaS",
    description: "Modern SaaS one-page landing with violet accents, dashboard hero, and feature grid.",
    category: "Tech",
    style: "Dark",
    tags: ["SaaS", "Landing", "Tech"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-114",
    name: "Terra Slider",
    description: "Full-screen curtain-reveal slider with nature photography and serif titles.",
    category: "Creative",
    style: "Dark",
    tags: ["Slider", "Curtain Reveal", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-115",
    name: "Verda Parallax",
    description: "Multi-speed parallax wave gallery with emerald tones and varied image depths.",
    category: "Creative",
    style: "Dark",
    tags: ["Gallery", "Parallax", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-116",
    name: "Kyoto Teahouse",
    description: "Serene Japanese teahouse menu with washi paper tones and kanji accents.",
    category: "Luxury",
    style: "Light",
    tags: ["Food", "Japanese", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-117",
    name: "Genesis Pharm",
    description: "AI drug discovery SPA with molecular target visualization, clinical pipeline telemetry, and emerald-biotech aesthetic.",
    category: "Tech",
    style: "Dark",
    tags: ["Pharma", "AI", "Biotech", "Telemetry"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-118",
    name: "Formwerk Studio",
    description: "Architecture studio SPA with blueprint grid overlay, parametric section drawings, and sky-blue industrial aesthetic.",
    category: "Tech",
    style: "Dark",
    tags: ["Architecture", "Studio", "Blueprint", "Telemetry"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-119",
    name: "IronX Fitness",
    description: "Elite fitness SPA with heart rate visualization, leaderboard tracker, combat programs, and red-industrial aesthetic.",
    category: "Creative",
    style: "Dark",
    tags: ["Fitness", "Gym", "Leaderboard", "Combat"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-120",
    name: "Éclat Parfum",
    description: "Luxury perfume house SPA with molecule visualization, expanding scent rings, rare botanicals, and deep plum-purple aesthetic.",
    category: "Luxury",
    style: "Dark",
    tags: ["Perfume", "Luxury", "Fragrance", "Botanical"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-121",
    name: "Folio Studio",
    description: "Creative portfolio SPA with hover-reveal project list, services grid, awards section, and clean monochrome light-theme aesthetic.",
    category: "Creative",
    style: "Light",
    tags: ["Portfolio", "Studio", "Awards", "Monochrome"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-122",
    name: "Chronicle Editorial",
    description: "Editorial magazine SPA with reading progress bar, featured long-read cards, serif typography, and amber-editorial aesthetic.",
    category: "Editorial",
    style: "Light",
    tags: ["Editorial", "Magazine", "Long-Form", "Journalism"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-123",
    name: "Maison Fashion",
    description: "Fashion house SPA with AW26 lookbook, atelier craftsmanship section, press quotes, and gold-couture aesthetic.",
    category: "Luxury",
    style: "Dark",
    tags: ["Fashion", "Couture", "Lookbook", "Atelier"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-124",
    name: "Morph Studio",
    description: "Motion design studio SPA with morphing blob hero, scroll-linked scale, project list hover effects, and fuchsia-creative aesthetic.",
    category: "Creative",
    style: "Dark",
    tags: ["Motion", "Studio", "Real-Time", "Film"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-125",
    name: "Aura Interactive",
    description: "Interactive design lab SPA with custom cursor aura, radar sweep, haptic research grid, and cyan-interactive aesthetic.",
    category: "Tech",
    style: "Dark",
    tags: ["Interactive", "Haptic", "Installation", "Lab"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-126",
    name: "Trattoria Menu",
    description: "Italian restaurant tabbed menu with warm leather tones and orange accents.",
    category: "Luxury",
    style: "Dark",
    tags: ["Food", "Menu", "Italian"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-127",
    name: "Pulse Events",
    description: "Live events SPA with equalizer bars, pulsing status indicators, event list hover effects, and neon pink-concert aesthetic.",
    category: "Creative",
    style: "Dark",
    tags: ["Events", "Music", "Festival", "Neon"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-128",
    name: "Haven Estates",
    description: "Luxury real estate SPA with property card grid, listing specs, investment advisory, and warm gold-on-cream light-theme aesthetic.",
    category: "Luxury",
    style: "Light",
    tags: ["Real Estate", "Luxury", "Listings", "Investment"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-129",
    name: "Wave FX",
    description: "Open-source dev tools SPA with animated sine waves, code snippets, telemetry dashboard, and indigo-developer aesthetic.",
    category: "Tech",
    style: "Dark",
    tags: ["DevTools", "Open-Source", "WebGL", "SDK"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-130",
    name: "Split Reveal",
    description: "Split-screen slider with left image and right content, emerald accents.",
    category: "Creative",
    style: "Dark",
    tags: ["Slider", "Split", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-131",
    name: "Cuvée Prestige",
    description: "Wine showcase hero with deep burgundy tones, vineyard backdrop, and bottle presentation.",
    category: "Luxury",
    style: "Dark",
    tags: ["Wine", "Luxury", "Showcase"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-132",
    name: "Elementum",
    description: "Clean alternating-row portfolio with nature imagery and ultra-light typography.",
    category: "Minimal",
    style: "Light",
    tags: ["Portfolio", "Alternating", "Minimal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-133",
    name: "Atlas Zoom",
    description: "Dramatic zoom-out reveal hero with city skyline and sky-blue accents.",
    category: "Creative",
    style: "Dark",
    tags: ["Hero", "Zoom", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-134",
    name: "Lumière Beauty",
    description: "Beauty/skincare e-commerce grid with peach tones and rose accent tags.",
    category: "Luxury",
    style: "Light",
    tags: ["Beauty", "E-commerce", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-135",
    name: "Trade OS",
    description: "Live stock ticker dashboard with dynamic data updates, green/red indicators.",
    category: "Tech",
    style: "Dark",
    tags: ["Fintech", "Dashboard", "Tech"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-136",
    name: "Text Reveal",
    description: "Text mask scroll reveal where background image expands through scroll-linked inset clip-path.",
    category: "Creative",
    style: "Dark",
    tags: ["Scroll Reveal", "Text Mask", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-137",
    name: "Torréfié Coffee",
    description: "Specialty coffee roaster one-page with warm paper tones and origin card grid.",
    category: "Minimal",
    style: "Light",
    tags: ["Coffee", "One-Page", "Minimal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-138",
    name: "Prism Analytics",
    description: "Glassmorphism analytics dashboard with gradient background, bar chart, and metric cards.",
    category: "Tech",
    style: "Dark",
    tags: ["Analytics", "Dashboard", "Tech"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-139",
    name: "Apex Automotive",
    description: "Luxury automotive SPA with model selector tabs, performance telemetry bars, RPM gauge animation, and red-industrial motorsport aesthetic.",
    category: "Luxury",
    style: "Dark",
    tags: ["Automotive", "Luxury", "Performance", "Configurator"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-140",
    name: "Wanderlust",
    description: "Travel agency hero with destination cards, amber accents, and full-bleed landscape.",
    category: "Minimal",
    style: "Dark",
    tags: ["Travel", "Hero", "Minimal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-141",
    name: "Sonic Player",
    description: "Music player hero with album art, progress bar, and purple glow effects.",
    category: "Creative",
    style: "Dark",
    tags: ["Music", "Player", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-142",
    name: "Verdant Impact",
    description: "Sustainability landing page with features grid, impact metrics, testimonials, pricing table, contact form, and green-earth light aesthetic.",
    category: "Minimal",
    style: "Light",
    tags: ["Sustainability", "Landing", "Pricing", "Contact"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-143",
    name: "Atelier Interior",
    description: "Interior design site vitrine with about section, services grid, portfolio showcase, testimonials, and warm taupe-luxury light aesthetic.",
    category: "Luxury",
    style: "Light",
    tags: ["Interior", "Vitrine", "Portfolio", "Services"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-144",
    name: "Kinetic Marquee",
    description: "Kinetic typography landing page with dual marquee bands, features grid, testimonials, pricing table, and orange-creative dark aesthetic.",
    category: "Creative",
    style: "Dark",
    tags: ["Typography", "Landing", "Pricing", "Testimonials"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-145",
    name: "Deepcast",
    description: "Podcast landing with episode list, play buttons, and yellow accent on deep navy.",
    category: "Creative",
    style: "Dark",
    tags: ["Podcast", "Landing", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-146",
    name: "Velos FinTech",
    description: "Crypto wallet landing page with portfolio dashboard mockup, features grid, testimonials, pricing plans, and cyan-fintech dark aesthetic.",
    category: "Tech",
    style: "Dark",
    tags: ["FinTech", "Crypto", "Landing", "Pricing"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-147",
    name: "Void Arch",
    description: "Minimalist Black & White architecture portfolio with staggered layout and grayscale-to-color reveals.",
    category: "Minimal",
    style: "Light",
    tags: ["Architecture", "Portfolio", "B&W"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-148",
    name: "Pureté Skincare",
    description: "Organic skincare storytelling with soft cream tones, delicate serif typography, and botanical atmosphere.",
    category: "Luxury",
    style: "Light",
    tags: ["Skincare", "Storytelling", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-149",
    name: "Nørdic Furniture",
    description: "High-end furniture showcase with 3D perspective transitions and bold italic typography.",
    category: "Luxury",
    style: "Dark",
    tags: ["Furniture", "3D", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-150",
    name: "Neon Unit Apparel",
    description: "Cyberpunk-themed apparel shop with neon cyan accents, glitch aesthetic, and technical data overlays.",
    category: "Tech",
    style: "Dark",
    tags: ["Cyberpunk", "Apparel", "E-commerce"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-151",
    name: "Chronos Lab",
    description: "Luxury watch technical detail page with scroll-linked zoom, HUD-inspired overlays, and bold italic typography.",
    category: "Luxury",
    style: "Dark",
    tags: ["Watch", "Technical", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-152",
    name: "Wanderer Mag",
    description: "Travel magazine site vitrine with about, destinations grid, services, testimonials, pricing plans, newsletter, and warm amber-cream aesthetic.",
    category: "Editorial",
    style: "Light",
    tags: ["Travel", "Vitrine", "Pricing", "Testimonials"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-153",
    name: "Véloce Team",
    description: "Engineering agency landing page with features grid, stats counters, testimonials, pricing tiers, and purple-tech dark aesthetic.",
    category: "Tech",
    style: "Dark",
    tags: ["Agency", "Landing", "Pricing", "Tech"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-154",
    name: "Obliq Services",
    description: "Creative agency site vitrine with about, services grid, portfolio, testimonials, pricing, and rose-crimson dark aesthetic.",
    category: "Creative",
    style: "Dark",
    tags: ["Agency", "Vitrine", "Portfolio", "Pricing"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-155",
    name: "Art Index",
    description: "Digital art gallery landing with collections, features grid, testimonials, membership pricing, and purple-creative dark aesthetic.",
    category: "Creative",
    style: "Dark",
    tags: ["Art", "Gallery", "Landing", "Pricing"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-156",
    name: "Bio Form Arch",
    description: "Sustainable architecture site vitrine with about, project portfolio, services grid, testimonials, and sage-green light aesthetic.",
    category: "Minimal",
    style: "Light",
    tags: ["Architecture", "Vitrine", "Services", "Sustainability"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-157",
    name: "Aurum Jewelry",
    description: "Ultra-premium jewelry e-commerce detail page with deep obsidian tones, gold accents, and a focus on high-end sculptural photography.",
    category: "Luxury",
    style: "Dark",
    tags: ["Jewelry", "E-commerce", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-158",
    name: "Atlas — Journal de Voyage",
    description: "Carnet de voyage éditorial — héros split avec postcards empilés en rotation, parallaxe bi-axiale, archive d'articles en lignes horizontales et grille de destinations avec reveal au survol.",
    category: "Editorial",
    style: "Light",
    tags: ["Travel", "Editorial", "Blog", "Parallax"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-159",
    name: "Re Con Tech",
    description: "High-energy tech event landing with dynamic countdown, neon gradient accents, and immersive particle-style background effects.",
    category: "Tech",
    style: "Dark",
    tags: ["Event", "Tech", "Countdown"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-160",
    name: "Maison V Lookbook",
    description: "Minimalist staggered fashion lookbook with high-contrast monochrome design, hover effects, and bold heroic headings.",
    category: "Minimal",
    style: "Light",
    tags: ["Fashion", "Lookbook", "Minimal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-161",
    name: "Essential SaaS",
    description: "Clean SaaS Landing Page with WordPress/Elementor-ready semantic HTML block structure.",
    category: "Free",
    style: "Light",
    tags: ["SaaS", "Landing", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-162",
    name: "Essential Cafe",
    description: "Local Cafe theme with warm colors, classic layout, and direct WordPress container mapping.",
    category: "Free",
    style: "Light",
    tags: ["Local Business", "Food", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-163",
    name: "L'Essentiel",
    description: "Blog éditorial style journal — grille newspaper asymétrique, articles héros avec date en marge, filtrage par catégories, typographie vieille presse et parallaxe de fond.",
    category: "Editorial",
    style: "Light",
    tags: ["Blog", "Editorial", "Newspaper", "Typography"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-164",
    name: "Bureau",
    description: "Agence créative brutaliste — typographie monospace, grille 2 colonnes asymétrique, marquee en scroll horizontal, liste de services expand-on-hover et sélecteur de case studies.",
    category: "Creative",
    style: "Dark",
    tags: ["Agency", "Brutalist", "Monospace", "Portfolio"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-165",
    name: "Pulse App",
    description: "Landing SaaS mobile app — maquette téléphone avec parallaxe de scale au scroll, tabs fonctionnalités AnimatePresence, section témoignages sombre et pricing 3 niveaux en pilules.",
    category: "Tech",
    style: "Light",
    tags: ["SaaS", "Mobile", "App", "Landing"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-166",
    name: "Iris Studio",
    description: "Portfolio photographe cinématographique — overlay grain SVG animé, parallaxe de texte héros avec opacité, grille de séries avec reveal couleur or au survol et services en 2 colonnes serif.",
    category: "Creative",
    style: "Dark",
    tags: ["Photography", "Portfolio", "Cinematic", "Serif"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-167",
    name: "Rive Gauche Immobilier",
    description: "Agence immobilière prestige — héros split marine/ivoire, cartes propriétés avec highlight or actif, double parallaxe fond et texte, stats en Cormorant Garamond doré sur marine.",
    category: "Luxury",
    style: "Light",
    tags: ["Real Estate", "Luxury", "Serif", "Agency"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-168",
    name: "Éclat",
    description: "Boutique mode éditoriale — barre d'annonce, héros plein écran sombre, grille produits avec wishlist cœur et counter add-to-cart, zoom hover image et newsletter en pied de section.",
    category: "E-Commerce",
    style: "Light",
    tags: ["Fashion", "E-Commerce", "Editorial", "Boutique"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-169",
    name: "Fréquence",
    description: "Publication média newsletter — layout newspaper avec sidebar catégories vertical, logo en rotation scroll, archive d'issues cliquables en liste et split subscription jaune/sombre.",
    category: "Editorial",
    style: "Dark",
    tags: ["Newsletter", "Media", "Newspaper", "Editorial"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-170",
    name: "Rafaël Moreau",
    description: "Portfolio développeur terminal — animations de frappe séquencées, barres de compétences en useInView, timeline carrière verticale et project cards avec reveal cible au survol.",
    category: "Creative",
    style: "Dark",
    tags: ["Portfolio", "CV", "Terminal", "Developer"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-171",
    name: "Vitalité Médical",
    description: "Clinique médicale moderne — héros split avec cards spécialistes flottantes en stagger, tabs spécialités AnimatePresence, stats teal plein fond et pricing avec scale highlight.",
    category: "Health",
    style: "Light",
    tags: ["Medical", "Clinic", "Healthcare", "Booking"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-172",
    name: "Legrand & Associés",
    description: "Cabinet d'avocats prestige — héros 3:2 avec titre italique oversized, sidebar domaines avec panel AnimatePresence, associés en grille avec ligne dorée absolue en haut.",
    category: "Corporate",
    style: "Dark",
    tags: ["Law", "Legal", "Serif", "Corporate"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-173",
    name: "Structure Bâtisseurs",
    description: "BTP industriel bold — titre full-width clamp(64px, 11vw, 160px) en capitales, panel diagonal orange clipPath, barres de progression de projets animées et services en icônes carrées.",
    category: "Services",
    style: "Dark",
    tags: ["Construction", "Industrial", "Bold", "BTP"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-174",
    name: "FORGE",
    description: "Salle de sport haute intensité — héros split 50/50 noir/lime neon, barres d'intensité 4 dimensions en useInView, programmes actifs avec border accent et CTA lime full-width.",
    category: "Services",
    style: "Dark",
    tags: ["Fitness", "Gym", "Bold", "Sport"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-175",
    name: "Confluence Events",
    description: "Agence événementielle prestige — héros centré avec cercles décoratifs absolus, sélecteur de types d'événements multi-accents, timeline 4 étapes verticale et stats en plum avec chiffres en serif.",
    category: "Services",
    style: "Light",
    tags: ["Events", "Agency", "Wedding", "Luxury"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-176",
    name: "Metric",
    description: "SaaS analytics B2B — maquette dashboard héros avec graphe SVG animé (pathLength), indicateur live pulsant, grille features 3×2 avec badge métriques et pricing Growth en scale highlight.",
    category: "Tech",
    style: "Dark",
    tags: ["SaaS", "Analytics", "Dashboard", "B2B"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-177",
    name: "Essential Podcast",
    description: "Tech Podcast landing page with elegant dark mode, audio player hints, and list block.",
    category: "Free",
    style: "Dark",
    tags: ["Podcast", "Media", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-178",
    name: "Essential Cleaning",
    description: "Light and Trustworthy Cleaning Service landing page with review badges and ZIP code form.",
    category: "Free",
    style: "Light",
    tags: ["Service", "Local Business", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-179",
    name: "Essential Non-profit",
    description: "Non-profit charity landing page with emotional photography, serif headers, and donation CTA.",
    category: "Free",
    style: "Light",
    tags: ["Charity", "Non-profit", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-180",
    name: "Essential Salon",
    description: "Premium Barber/Salon split-screen layout with dark aesthetic and price list.",
    category: "Free",
    style: "Dark",
    tags: ["Salon", "Barber", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-181",
    name: "Nexus Web3",
    description: "Premium Web3/Crypto landing page with floating ORB backgrounds, glassmorphism UI, and fluid animations.",
    category: "Tech",
    style: "Vibrant",
    tags: ["Web3", "Crypto", "DeFi"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-182",
    name: "The Grand Hotel",
    description: "Premium Luxury Hotel landing page with elegant serif fonts, parallax feels, and large immersive photography.",
    category: "Luxury",
    style: "Light",
    tags: ["Hotel", "Travel", "Elegant"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-183",
    name: "Cognix AI",
    description: "Premium AI SaaS Platform featuring neumorphic glass impacts, dark mode glows, and generative interface hints.",
    category: "Tech",
    style: "Dark",
    tags: ["AI", "SaaS", "Dashboard"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-184",
    name: "MoMA Structure",
    description: "Premium Modern Museum with Brutalist sidebar layout, extreme typography and solid borders.",
    category: "Creative",
    style: "Light",
    tags: ["Museum", "Art", "Brutalist"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-185",
    name: "Velma Editorial",
    description: "Premium Fashion Brand layout featuring massive hero text blending with background photography.",
    category: "Editorial",
    style: "Light",
    tags: ["Fashion", "Lookbook", "Oversized Text"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-186",
    name: "ArchiTectura",
    description: "Premium Architecture firm structural grid with brutalist grayscale hover reveals.",
    category: "Minimal",
    style: "Dark",
    tags: ["Architecture", "Studio", "Grayscale"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-187",
    name: "Vault FinTech",
    description: "Premium FinTech Interface with glowing charts, deep blue/emerald gradients, and glassmorphism.",
    category: "Tech",
    style: "Dark",
    tags: ["FinTech", "App", "Gradients"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-188",
    name: "Cinema Roster",
    description: "Premium Film Production horizontal-scroll aesthetic with cinematic typography and giant cinematic tiles.",
    category: "Creative",
    style: "Dark",
    tags: ["Film", "Production", "Horizontal Scroll"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-189",
    name: "Aura Dining",
    description: "Premium Restaurant/Dining layout with dark romantic themes, elegant thin serifs, and tall image masks.",
    category: "Luxury",
    style: "Dark",
    tags: ["Restaurant", "Dining", "Romantic"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-190",
    name: "Nexus Gaming",
    description: "Premium Cyberpunk/Gaming Studio landing page with neon grid effects, glitch-inspired text, and stark lines.",
    category: "Tech",
    style: "Dark",
    tags: ["Gaming", "Cyberpunk", "Neon"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-191",
    name: "Nova Clinic",
    description: "Premium healthcare and aesthetics clinic with a clean, trust-building layout and appointment booking focus.",
    category: "Services",
    style: "Light",
    tags: ["Healthcare", "Clinic", "Medical"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-192",
    name: "Lumina Beauty",
    description: "High-end cosmetics e-commerce template with dynamic product grids, texture reveals, and cart drawer.",
    category: "E-Commerce",
    style: "Light",
    tags: ["Beauty", "Cosmetics", "E-Commerce"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-193",
    name: "Sterling Partners",
    description: "Premium corporate law firm and consulting layout with serif typography and authoritative design.",
    category: "Corporate",
    style: "Dark",
    tags: ["Law", "Consulting", "Corporate"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-194",
    name: "The Gravity Forge",
    description: "Advanced artificial gravity and singularity engineering interface with real-time curvature metrics and tidal force monitors.",
    category: "Tech",
    style: "Dark",
    tags: ["Gravity", "Singularity", "Physics", "HUD"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-195",
    name: "The Atmos Shield",
    description: "Planetary-scale atmospheric capture and climate engineering interface with carbon titration and albedo control systems.",
    category: "Tech",
    style: "Dark",
    tags: ["Climate", "Atmosphere", "Sustainability", "HUD"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-196",
    name: "The Bio-Robot",
    description: "Advanced cybernetic enhancement and biomimetic limb integration interface with neural latency and force metrics.",
    category: "Tech",
    style: "Dark",
    tags: ["Cybernetics", "Bionics", "Neural", "HUD"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-197",
    name: "Évasion Dorée",
    description: "Luxury travel agency landing page — bespoke itineraries, parallax hero, destination cards, concierge services & 3-tier pricing.",
    category: "Luxury",
    style: "Dark",
    tags: ["Travel", "Luxury", "Agency"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-198",
    name: "Lumière Beauty",
    description: "Premium beauty salon vitrine — bio & natural products, treatments grid, team tabs, testimonials carousel & seasonal packages.",
    category: "Services",
    style: "Light",
    tags: ["Beauty", "Spa", "Wellness"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-199",
    name: "Encre & Âme",
    description: "Artistic tattoo studio — six style showcase, 3 artist profiles, flash & custom pricing, dark editorial aesthetic.",
    category: "Creative",
    style: "Dark",
    tags: ["Tattoo", "Art", "Studio"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-200",
    name: "Cérémonie",
    description: "Wedding planner landing page — gallery of past events, full coordination services, 3-tier packages & romantic aesthetic.",
    category: "Services",
    style: "Light",
    tags: ["Wedding", "Events", "Luxury"],
    tier: "Premium",
    sections: 9,
  },
  {
    id: "impact-201",
    name: "Maison Saveur",
    description: "Private chef vitrine — gourmet at-home dining, seasonal menus, Michelin-trained chef, event catering & testimonials.",
    category: "Food",
    style: "Dark",
    tags: ["Chef", "Gastronomy", "Private"],
    tier: "Premium",
    sections: 9,
  },
];
