"use client";
import { motion, useInView, AnimatePresence } from "framer-motion";
import { useState, useRef, useEffect } from "react";
import Link from "next/link";
import { Hexagon, Shield, Zap, Menu, X, Star, CheckCircle2, Lock, BarChart3, Globe } from "lucide-react";
import "../premium.css";
const FEAT=[{icon:<Shield className="w-6 h-6"/>,t:"Audited Contracts",d:"Every smart contract triple-audited by Certik and Trail of Bits."},{icon:<Zap className="w-6 h-6"/>,t:"Instant Swaps",d:"Sub-second cross-chain swaps with zero slippage protection."},{icon:<Lock className="w-6 h-6"/>,t:"Self-Custody",d:"Your keys, your crypto. Non-custodial by design."},{icon:<BarChart3 className="w-6 h-6"/>,t:"Yield Vaults",d:"Auto-compounding strategies across 15+ protocols."},{icon:<Globe className="w-6 h-6"/>,t:"Multi-Chain",d:"Ethereum, Solana, Arbitrum, Base — all in one interface."},{icon:<Hexagon className="w-6 h-6"/>,t:"Governance",d:"Vote on protocol upgrades with $NXS token."}];
const STATS=[{v:"$2.4B",l:"TVL"},{v:"180K+",l:"WALLETS"},{v:"99.99%",l:"UPTIME"},{v:"$0",l:"HACKS"}];
const TM=[{n:"0xAlpha.eth",r:"DeFi Trader",q:"Nexus has the smoothest UX of any DEX. My go-to for all trades."},{n:"CryptoSara",r:"Yield Farmer",q:"The vaults consistently outperform. Set and forget with real returns."},{n:"BlockDev",r:"Protocol Engineer",q:"Clean contracts, transparent governance. This is how DeFi should be built."}];
const PR=[{n:"FREE",p:"$0",pd:"",f:["Unlimited swaps","Basic vaults","Community support","Governance voting"],c:"Launch_App"},{n:"PRO",p:"$29",pd:"/mo",f:["Priority execution","Advanced vaults","Analytics dashboard","API access","Limit orders"],c:"Go_Pro",ft:true},{n:"WHALE",p:"$199",pd:"/mo",f:["OTC desk access","Custom strategies","Dedicated PM","White-glove onboarding","Private Telegram"],c:"Apply"}];
function Reveal({children,delay=0}:{children:React.ReactNode;delay?:number}){const ref=useRef(null);const iv=useInView(ref,{once:true,margin:"-50px"});return<motion.div ref={ref} initial={{opacity:0,y:20}} animate={iv?{opacity:1,y:0}:{}} transition={{duration:0.8,delay}}>{children}</motion.div>;}
export default function NexusWeb3Page(){
  const[s,setS]=useState(false);const[m,setM]=useState(false);
  useEffect(()=>{const h=()=>setS(window.scrollY>50);window.addEventListener("scroll",h);return()=>window.removeEventListener("scroll",h);},[]);
  return(<div className="premium-theme min-h-screen bg-[#05050a] text-white font-mono selection:bg-[#06b6d4] selection:text-black overflow-x-hidden">
    <div className="fixed inset-0 pointer-events-none z-0"><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_50%_0%,#06b6d418_0%,transparent_40%)]"/><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_80%_80%,#8b5cf615_0%,transparent_40%)]"/></div>
    <nav className={`fixed top-0 left-0 w-full z-50 transition-all duration-500 ${s?"bg-[#05050a]/90 backdrop-blur-xl py-4 border-b border-white/5":"bg-transparent py-10"}`}><div className="max-w-[1500px] mx-auto px-6 md:px-12 flex items-center justify-between"><Link href="/" className="group flex items-center gap-3 text-xl font-black tracking-tighter"><div className="w-8 h-8 bg-gradient-to-br from-[#06b6d4] to-[#8b5cf6] rounded-lg flex items-center justify-center text-white"><Hexagon className="w-4 h-4"/></div><span className="group-hover:text-[#06b6d4] transition-colors">NEXUS // <span className="text-white/30">WEB3</span></span></Link><div className="hidden lg:flex items-center gap-10 text-[10px] font-bold uppercase tracking-[0.3em] text-white/30">{["Protocol","Vaults","Docs","Governance"].map(l=><Link key={l} href="#" className="hover:text-[#06b6d4] transition-colors">{l}</Link>)}</div><button className="px-6 py-2.5 bg-gradient-to-r from-[#06b6d4] to-[#8b5cf6] text-white text-[10px] font-black uppercase tracking-widest hover:opacity-80 transition-all hidden md:block">Launch_App</button><button onClick={()=>setM(true)} className="lg:hidden"><Menu className="w-6 h-6"/></button></div></nav>
    <AnimatePresence>{m&&(<motion.div initial={{opacity:0,x:"100%"}} animate={{opacity:1,x:0}} exit={{opacity:0,x:"100%"}} className="fixed inset-0 z-[100] bg-[#05050a] p-8 flex flex-col pt-32"><button onClick={()=>setM(false)} className="absolute top-10 right-8"><X className="w-10 h-10"/></button>{["Protocol","Vaults","Docs","Governance"].map(l=><Link key={l} href="#" onClick={()=>setM(false)} className="text-5xl font-black tracking-tighter uppercase mb-10">{l}</Link>)}</motion.div>)}</AnimatePresence>

    <section className="relative min-h-screen flex flex-col justify-center pt-20"><div className="max-w-[1500px] mx-auto px-6 md:px-12 relative z-10"><Reveal><div className="px-3 py-1 bg-[#06b6d4]/10 border border-[#06b6d4]/30 text-[#06b6d4] text-[9px] font-bold uppercase tracking-widest inline-block mb-8">DEFI_PROTOCOL_V3</div><h1 className="text-7xl md:text-9xl lg:text-[10rem] font-black leading-[0.8] tracking-tighter uppercase mb-10">The<br/>Future<br/>Is <span className="bg-gradient-to-r from-[#06b6d4] to-[#8b5cf6] bg-clip-text text-transparent">Onchain.</span></h1><p className="max-w-xl text-lg text-white/30 leading-relaxed font-light uppercase tracking-widest italic mb-12">Swap, earn, and govern across every major chain. Self-custody. Always.</p><div className="flex flex-col sm:flex-row gap-6"><button className="px-12 py-5 bg-gradient-to-r from-[#06b6d4] to-[#8b5cf6] text-white text-[10px] font-black uppercase tracking-[0.4em] hover:opacity-80 transition-all shadow-[0_0_50px_rgba(6,182,212,0.15)]">Launch_App</button><button className="px-12 py-5 border border-white/10 text-[10px] font-black uppercase tracking-[0.4em] hover:bg-white hover:text-black transition-all">Read_Docs</button></div></Reveal></div></section>

    <section className="py-32 bg-[#08080f] border-y border-white/5"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><div className="grid grid-cols-2 md:grid-cols-4 gap-16 text-center">{STATS.map((s,i)=><div key={i} className="group"><div className="text-4xl md:text-5xl font-black bg-gradient-to-r from-[#06b6d4] to-[#8b5cf6] bg-clip-text text-transparent mb-2">{s.v}</div><div className="text-[9px] font-black text-white/15 uppercase tracking-widest">{s.l}</div></div>)}</div></Reveal></div></section>

    <section className="py-40 bg-[#05050a]"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter uppercase leading-[0.85] mb-24">Protocol <span className="bg-gradient-to-r from-[#06b6d4] to-[#8b5cf6] bg-clip-text text-transparent">Features.</span></h2></Reveal><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-8">{FEAT.map((f,i)=><Reveal key={i} delay={i*0.05}><div className="group p-10 bg-[#08080f] border border-white/5 hover:border-[#06b6d4]/30 rounded-3xl transition-all"><div className="w-14 h-14 bg-white/5 rounded-2xl flex items-center justify-center text-[#06b6d4] mb-8 group-hover:bg-gradient-to-br group-hover:from-[#06b6d4] group-hover:to-[#8b5cf6] group-hover:text-white transition-all">{f.icon}</div><h3 className="text-xl font-black uppercase tracking-tighter mb-4 group-hover:text-[#06b6d4] transition-colors">{f.t}</h3><p className="text-sm text-white/30">{f.d}</p></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-[#08080f] border-y border-white/5"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter uppercase leading-[0.85] mb-24">Community <span className="text-[#06b6d4]">Voices.</span></h2></Reveal><div className="grid grid-cols-1 md:grid-cols-3 gap-8">{TM.map((t,i)=><Reveal key={i} delay={i*0.1}><div className="p-10 bg-[#0a0a12] border border-white/5 rounded-3xl h-full flex flex-col"><div className="flex gap-1 mb-6">{[...Array(5)].map((_,j)=><Star key={j} className="w-4 h-4 text-[#06b6d4] fill-[#06b6d4]"/>)}</div><p className="text-base text-white/40 italic leading-relaxed flex-1 mb-8">&ldquo;{t.q}&rdquo;</p><div className="pt-6 border-t border-white/5"><div className="font-black uppercase text-sm">{t.n}</div><div className="text-[10px] text-white/20 uppercase tracking-widest">{t.r}</div></div></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-[#05050a]"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-8xl font-black tracking-tighter leading-[0.85] mb-24 uppercase text-center">Access <span className="text-[#06b6d4]">Tiers.</span></h2></Reveal><div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl mx-auto">{PR.map((p,i)=><Reveal key={i} delay={i*0.1}><div className={`group p-10 border rounded-3xl transition-all ${p.ft?"bg-gradient-to-br from-[#06b6d4]/5 to-[#8b5cf6]/5 border-[#06b6d4]/30 scale-105":"bg-[#08080f] border-white/5"}`}><div className="text-[9px] font-bold text-[#06b6d4] uppercase tracking-widest mb-2">{p.n}</div><div className="text-4xl font-black mb-1">{p.p}<span className="text-lg text-white/30">{p.pd}</span></div><div className="space-y-4 mt-8 pt-8 border-t border-white/5">{p.f.map((f,j)=><div key={j} className="flex items-center gap-3 text-[10px] text-white/40"><CheckCircle2 className="w-3.5 h-3.5 text-[#06b6d4]"/>{f}</div>)}</div><button className={`mt-8 w-full py-3 text-[10px] font-black uppercase tracking-widest transition-all rounded-lg ${p.ft?"bg-gradient-to-r from-[#06b6d4] to-[#8b5cf6] text-white":"border border-white/10 hover:bg-[#06b6d4] hover:text-white"}`}>{p.c}</button></div></Reveal>)}</div></div></section>

    <section className="py-40 bg-[#08080f] text-center border-t border-white/5"><div className="max-w-[1500px] mx-auto px-6 md:px-12"><Reveal><h2 className="text-6xl md:text-9xl font-black tracking-tighter uppercase mb-12">Go <span className="bg-gradient-to-r from-[#06b6d4] to-[#8b5cf6] bg-clip-text text-transparent">Onchain.</span></h2><button className="px-16 py-6 bg-gradient-to-r from-[#06b6d4] to-[#8b5cf6] text-white text-[12px] font-black uppercase tracking-[0.4em] hover:opacity-80 transition-all shadow-[0_0_60px_rgba(6,182,212,0.1)]">Connect_Wallet</button></Reveal></div></section>

    <footer className="bg-[#05050a] border-t border-white/5 py-32 px-6 md:px-12"><div className="max-w-[1500px] mx-auto grid grid-cols-1 md:grid-cols-4 gap-24"><div className="col-span-1 md:col-span-2"><Link href="/" className="flex items-center gap-3 text-xl font-black tracking-tighter mb-10"><div className="w-8 h-8 bg-gradient-to-br from-[#06b6d4] to-[#8b5cf6] text-white rounded-lg flex items-center justify-center"><Hexagon className="w-4 h-4"/></div><span>NEXUS // WEB3</span></Link><p className="text-[11px] text-white/15 uppercase tracking-[0.2em] max-w-sm italic">DeFi protocol. Multi-chain.</p></div><div><h4 className="text-[10px] font-black uppercase tracking-widest mb-10 text-[#06b6d4]">Protocol</h4><ul className="space-y-5 text-[10px] font-bold text-white/20 uppercase tracking-widest">{["Swap","Vaults","Governance"].map(l=><li key={l}><Link href="#">{l}</Link></li>)}</ul></div><div><h4 className="text-[10px] font-black uppercase tracking-widest mb-10 text-[#06b6d4]">Community</h4><ul className="space-y-5 text-[10px] font-bold text-white/20 uppercase tracking-widest">{["Discord","Twitter","GitHub"].map(l=><li key={l}><Link href="#">{l}</Link></li>)}</ul></div></div><div className="max-w-[1500px] mx-auto mt-32 pt-16 border-t border-white/5 text-center text-[9px] font-bold text-white/10 uppercase tracking-widest">&copy; 2026 NEXUS PROTOCOL</div></footer>
  </div>);
}
